// Eigenständig redaktionell erstellte Sammlung der 50 bekanntesten/meistgetrunkenen
// Cocktails. Rezepte, Zubereitung und Geschichte sind eigene Formulierungen auf Basis
// allgemein bekannten Cocktail-Wissens (IBA-Standards, klassische Barliteratur), keine
// Übernahme von Texten Dritter.
//
// Zutatennamen sind auf die tatsächlich geführten Produkte aus productsData.js gemappt
// (mit dem Barbesitzer abgestimmt), damit Aromenmatrix/Verkaufsmatrix/Empfehlungssystem
// die Rezepte korrekt zuordnen können. Frische Zutaten (Limette, Minze, Zitrone etc.)
// bleiben bewusst generisch, da sie nicht als Katalogprodukt geführt werden.
export const CLASSIC_RECIPES = [
  {
    name: "Old Fashioned",
    basePortions: 1,
    ingredients: [
      { name: "Bulleit Bourbon", amount: 60, unit: "ml" },
      { name: "Zuckersirup (2:1)", amount: 10, unit: "ml" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
    ],
    method: "Im Rührglas mit viel Eis kurz verrühren, auf einen großen Eiswürfel abseihen.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Orangenzeste",
    history: "Der Old Fashioned gilt als einer der ältesten benannten Cocktails und geht auf die ursprüngliche Definition von 'Cocktail' aus dem frühen 19. Jahrhundert zurück: Spirituose, Zucker, Bitters und Wasser. Der Name entstand, weil Gäste Ende des 19. Jahrhunderts genau diese schlichte, 'altmodische' Zubereitung gegenüber neumodischen Cocktails einforderten. Populär wurde er unter anderem im Pendennis Club in Louisville, Kentucky. Bis heute gilt er als Inbegriff des klassischen Whiskey-Cocktails.",
    pairsWith: ["Manhattan", "Sazerac", "Boulevardier"],
  },
  {
    name: "Manhattan",
    basePortions: 1,
    ingredients: [
      { name: "Sazerac Rye", amount: 60, unit: "ml" },
      { name: "Antica Formula", amount: 30, unit: "ml" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
    ],
    method: "Im Rührglas mit Eis rühren, in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale (Martini-Glas)",
    garnish: "Cocktailkirsche",
    history: "Der Manhattan entstand vermutlich in den 1870er- oder 1880er-Jahren in New York und ist nach dem Stadtteil benannt, in dem er das Licht der Bar-Welt erblickte. Eine bekannte, wenn auch unbelegte Legende schreibt seine Erfindung einem Bankett im Manhattan Club zu Ehren eines Präsidentschaftskandidaten zu. Die Kombination aus Whiskey, süßem Wermut und Bitters setzte den Standard für unzählige spätere Whiskey-Cocktails. Heute zählt er zu den meistbestellten klassischen Cocktails weltweit.",
    pairsWith: ["Old Fashioned", "Sazerac", "Boulevardier"],
  },
  {
    name: "Whiskey Sour",
    basePortions: 1,
    ingredients: [
      { name: "Bulleit Bourbon", amount: 60, unit: "ml" },
      { name: "Zitronensaft", amount: 25, unit: "ml" },
      { name: "Zuckersirup", amount: 20, unit: "ml" },
      { name: "Eiweiß", amount: 20, unit: "ml" },
    ],
    method: "Erst ohne Eis kräftig schütteln (dry shake), dann mit Eis erneut schütteln und abseihen.",
    glass: "Tumbler oder Cocktailschale",
    garnish: "Angostura-Tupfen, Cocktailkirsche",
    history: "Sour-Cocktails aus Spirituose, Zitrussaft und Zucker gehören zu den ältesten Cocktail-Familien und wurden bereits Mitte des 19. Jahrhunderts von Seeleuten getrunken, die Zitrussaft gegen Skorbut mitführten. Der Whiskey Sour selbst taucht erstmals 1862 in einem gedruckten Rezept auf. Die Variante mit Eiweiß, die dem Drink seine charakteristische cremige Textur gibt, setzte sich erst später durch. Er gilt bis heute als Blaupause für unzählige andere Sours.",
    pairsWith: ["Penicillin"],
  },
  {
    name: "Sazerac",
    basePortions: 1,
    ingredients: [
      { name: "Sazerac Rye", amount: 60, unit: "ml" },
      { name: "Zuckersirup", amount: 10, unit: "ml" },
      { name: "Angostura Bitters", amount: 3, unit: "dash" },
      { name: "Absinth (zum Ausspülen des Glases)", amount: 5, unit: "ml" },
    ],
    method: "Whiskey, Sirup und Bitters im Rührglas mit Eis rühren, in ein mit Absinth ausgespültes Glas abseihen.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Zitronenzeste (nur abreiben, nicht ins Glas)",
    history: "Der Sazerac aus New Orleans gilt vielen als der erste amerikanische Cocktail überhaupt und wurde ursprünglich mit Cognac statt Whiskey zubereitet. Benannt ist er nach der Sazerac-de-Forge-et-Fils-Cognac-Marke, die im gleichnamigen Sazerac Coffee House ausgeschenkt wurde. Als die Reblaus-Plage Ende des 19. Jahrhunderts europäische Weinberge zerstörte, wechselten Barkeeper auf amerikanischen Rye Whiskey. Louisiana erklärte den Sazerac später offiziell zum Signature-Cocktail von New Orleans. Klassisch wird der Sazerac mit Peychaud's Bitters zubereitet, die aktuell nicht im Sortiment geführt werden – hier ersetzt durch Angostura Bitters.",
    pairsWith: ["Old Fashioned", "Manhattan", "Boulevardier"],
  },
  {
    name: "Mint Julep",
    basePortions: 1,
    ingredients: [
      { name: "Bulleit Bourbon", amount: 60, unit: "ml" },
      { name: "Zuckersirup", amount: 10, unit: "ml" },
      { name: "Minzblätter", amount: 8, unit: "stk" },
    ],
    method: "Minze im Becher leicht anstoßen, mit Bourbon und Sirup auffüllen, mit zerstoßenem Eis füllen und verrühren.",
    glass: "Julep-Becher (Metallbecher)",
    garnish: "Großer Minzstrauß",
    history: "Der Mint Julep hat seine Wurzeln im amerikanischen Süden des 18. Jahrhunderts, wo er ursprünglich mit Rum oder Cognac zubereitet wurde, bevor sich Bourbon durchsetzte. Weltberühmt wurde er als offizieller Cocktail des Kentucky Derby, wo jährlich hunderttausende Becher ausgeschenkt werden. Der klassische Metallbecher beschlägt durch das zerstoßene Eis von außen mit Raureif, was zur zeremoniellen Wirkung beiträgt. Er gehört zu den ältesten bekannten Cocktail-Rezepten Amerikas.",
    pairsWith: ["Old Fashioned", "Manhattan", "Sazerac"],
  },
  {
    name: "Boulevardier",
    basePortions: 1,
    ingredients: [
      { name: "Bulleit Bourbon", amount: 30, unit: "ml" },
      { name: "Antica Formula", amount: 30, unit: "ml" },
      { name: "Campari", amount: 30, unit: "ml" },
    ],
    method: "Alle Zutaten im Rührglas mit Eis rühren und in ein Glas mit Eiswürfel abseihen.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Orangenzeste",
    history: "Der Boulevardier ist im Grunde ein Negroni mit Whiskey statt Gin und entstand vermutlich in den 1920er-Jahren im Paris der amerikanischen Expat-Szene. Erstmals schriftlich erwähnt wurde er 1927 in Harry McElhones Buch 'Barflies and Cocktails', benannt nach einer Pariser Zeitschrift. Jahrzehntelang eher ein Geheimtipp, erlebte er im Zuge der Craft-Cocktail-Bewegung der 2000er-Jahre eine große Renaissance. Heute zählt er zu den festen Klassikern jeder gut sortierten Whiskey-Bar.",
    pairsWith: ["Old Fashioned", "Manhattan", "Sazerac"],
  },
  {
    name: "Penicillin",
    basePortions: 1,
    ingredients: [
      { name: "Johnnie Walker Red Label", amount: 45, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
      { name: "Honig-Ingwer-Sirup", amount: 20, unit: "ml" },
      { name: "Laphroaig 10 Jahre (Floater)", amount: 7.5, unit: "ml" },
    ],
    method: "Scotch, Zitrone und Sirup mit Eis schütteln, abseihen, mit Islay-Whisky beschichten (floaten).",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Kandierter Ingwer",
    history: "Der Penicillin wurde 2005 von Sam Ross in der New Yorker Bar Milk & Honey erfunden und zählt zu den einflussreichsten modernen Cocktails überhaupt. Der Name spielt scherzhaft darauf an, dass Ingwer, Honig und Zitrone traditionell als Hausmittel gegen Erkältungen gelten. Der rauchige Islay-Whisky-Floater sorgt für ein intensives Aroma, das sich beim Trinken mit der süß-scharfen Basis verbindet. Er gilt als einer der meistkopierten Signature-Drinks des frühen 21. Jahrhunderts.",
    pairsWith: ["Whiskey Sour"],
  },
  {
    name: "Irish Coffee",
    basePortions: 1,
    ingredients: [
      { name: "Jameson Irish Whiskey", amount: 40, unit: "ml" },
      { name: "Brauner Zucker (oder Zuckersirup)", amount: 15, unit: "ml" },
      { name: "Heißer Kaffee", amount: 120, unit: "ml" },
      { name: "Schlagsahne (leicht geschlagen)", amount: 30, unit: "ml" },
    ],
    method: "Whiskey, Zucker und heißen Kaffee verrühren, vorsichtig mit leicht geschlagener Sahne unterlegen.",
    glass: "Irish-Coffee-Glas",
    garnish: "Sahneschicht, optional Muskatnuss",
    history: "Der Irish Coffee wurde in den 1940er-Jahren von Chefkoch Joe Sheridan im Flughafenrestaurant von Foynes in Irland erfunden, um frierenden Passagieren einzuheizen. In den 1950er-Jahren brachte der Reisejournalist Stanton Delaplane das Rezept in die Buena Vista Bar in San Francisco, von wo aus es sich in den USA verbreitete. Entscheidend ist die leicht geschlagene, kalte Sahne, die auf dem heißen, gesüßten Kaffee-Whiskey schwimmen bleibt. Er gilt bis heute als der bekannteste heiße Cocktail überhaupt.",
    pairsWith: ["White Russian", "Brandy Alexander", "Grasshopper"],
  },
  {
    name: "Martini",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 60, unit: "ml" },
      { name: "Martini Dry", amount: 10, unit: "ml" },
    ],
    method: "Im Rührglas mit viel Eis rühren, in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale (Martini-Glas)",
    garnish: "Olive oder Zitronenzeste",
    history: "Der Martini ist einer der bekanntesten Cocktails überhaupt, seine genaue Herkunft ist jedoch umstritten – Theorien reichen von einer Stadt namens Martinez in Kalifornien bis zur Wermut-Marke Martini & Rossi. Ursprünglich deutlich süßer, wurde er im Laufe des 20. Jahrhunderts zunehmend trockener, bis hin zum fast wermutlosen 'Extra Dry Martini'. James Bonds Vorliebe für den 'geschüttelt, nicht gerührt'-Martini machte den Drink weltberühmt, obwohl Puristen das Schütteln bis heute ablehnen. Er gilt als Inbegriff des eleganten, minimalistischen Cocktails.",
    pairsWith: ["Dirty Martini", "Martinez", "Negroni"],
  },
  {
    name: "Dirty Martini",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 60, unit: "ml" },
      { name: "Martini Dry", amount: 10, unit: "ml" },
      { name: "Olivenlake", amount: 10, unit: "ml" },
    ],
    method: "Im Rührglas mit Eis rühren, in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Oliven",
    history: "Der Dirty Martini ist eine Abwandlung des klassischen Martini, bei der etwas salziger Olivenlake hinzugefügt wird, was dem Drink seine namensgebende trübe ('dirty') Optik verleiht. Er entstand vermutlich um 1900 in New York, wurde aber erst deutlich später populär. Verschiedene Anekdoten schreiben seine Erfindung unterschiedlichen Barkeepern zu, ein eindeutiger Ursprung ist nicht belegt. Heute ist er vor allem bei Gästen beliebt, die eine kräftigere, herzhaftere Variante des klassischen Martini bevorzugen.",
    pairsWith: ["Martini", "Martinez", "Negroni"],
  },
  {
    name: "Negroni",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 30, unit: "ml" },
      { name: "Antica Formula", amount: 30, unit: "ml" },
      { name: "Campari", amount: 30, unit: "ml" },
    ],
    method: "Alle Zutaten im Rührglas mit Eis rühren und in ein Glas mit Eiswürfel abseihen.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Orangenzeste",
    history: "Der Negroni soll 1919 in Florenz entstanden sein, als Graf Camillo Negroni seinen Barkeeper bat, seinem gewohnten Americano mehr Wumms zu verleihen, indem Soda durch Gin ersetzt wurde. Ob diese Geschichte historisch exakt stimmt, ist umstritten, doch der Name blieb bis heute mit dem Drink verbunden. Die perfekte Drittelung aus Gin, Wermut und Campari machte ihn zu einem der ausbalanciertesten Aperitif-Cocktails überhaupt. In den letzten Jahren erlebte er weltweit eine regelrechte Renaissance.",
    pairsWith: ["Martini", "Dirty Martini", "Martinez"],
  },
  {
    name: "Gimlet",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 60, unit: "ml" },
      { name: "Limettensaft-Sirup", amount: 20, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Limettenscheibe",
    history: "Der Gimlet geht auf die britische Marine des 19. Jahrhunderts zurück, wo Matrosen Gin mit haltbarem Limettensaft-Cordial mischten, um Skorbut vorzubeugen. Der Name wird oft mit Marine-Chirurg Sir Thomas Gimlette in Verbindung gebracht. Raymond Chandlers Roman 'The Long Goodbye' machte den Drink 1953 zusätzlich literarisch berühmt. Bis heute wird diskutiert, ob ein klassischer Gimlet mit gesüßtem Limettencordial oder frischem Limettensaft zubereitet werden sollte.",
    pairsWith: ["Tom Collins", "Aviation", "Last Word"],
  },
  {
    name: "Tom Collins",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 50, unit: "ml" },
      { name: "Zitronensaft", amount: 25, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Schweppes Soda Water (zum Auffüllen)", amount: 60, unit: "ml" },
    ],
    method: "Gin, Zitrone und Sirup mit Eis schütteln, in ein Glas mit Eiswürfeln abseihen, mit Soda auffüllen.",
    glass: "Collins-Glas",
    garnish: "Zitronenscheibe, Cocktailkirsche",
    history: "Der Tom Collins geht auf die 'Collins'-Familie von Gin-Punsches zurück, die im 19. Jahrhundert in England und den USA populär waren. In den USA verbreitete sich ab den 1870er-Jahren ein Scherz namens 'Tom-Collins-Streich', bei dem Leuten erzählt wurde, ein gewisser Tom Collins habe schlecht über sie geredet – der Name blieb am Drink hängen. Die erfrischende Kombination aus Gin, Zitrus, Zucker und Soda machte ihn zu einem Sommer-Klassiker rund um die Welt. Heute ist er einer der bekanntesten Long Drinks der Cocktailgeschichte.",
    pairsWith: ["Gimlet", "Aviation", "Last Word"],
  },
  {
    name: "Aviation",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 45, unit: "ml" },
      { name: "Maraschino-Likör", amount: 15, unit: "ml" },
      { name: "Zitronensaft", amount: 15, unit: "ml" },
      { name: "Crème de Violette", amount: 5, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Cocktailkirsche",
    history: "Der Aviation wurde erstmals 1916 in Hugo Enslins Barbuch 'Recipes for Mixed Drinks' veröffentlicht, kurz nach den Anfangsjahren der zivilen Luftfahrt, worauf sich der Name bezieht. Crème de Violette verleiht ihm einen zarten Lavendelton, der optisch an einen wolkenverhangenen Himmel erinnert. Über Jahrzehnte geriet die Zutat in den USA in Vergessenheit, weshalb viele spätere Rezepte ohne sie auskamen. Erst mit ihrer Wiederverfügbarkeit ab den 2000er-Jahren erlebte der klassische Aviation eine Wiederentdeckung.",
    pairsWith: ["Gimlet", "Tom Collins", "Last Word"],
  },
  {
    name: "Last Word",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 20, unit: "ml" },
      { name: "Grüner Chartreuse", amount: 20, unit: "ml" },
      { name: "Maraschino-Likör", amount: 20, unit: "ml" },
      { name: "Limettensaft", amount: 20, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "ohne",
    history: "Der Last Word entstand vermutlich in den 1910er- oder 1920er-Jahren im Detroit Athletic Club und geriet danach für Jahrzehnte fast in Vergessenheit. Wiederentdeckt wurde er erst 2004 vom Seattle-Bartender Murray Stenson, der damit einen landesweiten Trend auslöste. Seine strikte Gleichteile-Formel aus Gin, Chartreuse, Maraschino und Limette wurde zur Blaupause für zahlreiche moderne Cocktail-Variationen. Heute gilt er als Paradebeispiel für die Wiederbelebung vergessener Klassiker der Craft-Cocktail-Bewegung.",
    pairsWith: ["Gimlet", "Tom Collins", "Aviation"],
  },
  {
    name: "French 75",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 30, unit: "ml" },
      { name: "Zitronensaft", amount: 15, unit: "ml" },
      { name: "Zuckersirup", amount: 10, unit: "ml" },
      { name: "Taittinger Brut Réserve (zum Auffüllen)", amount: 60, unit: "ml" },
    ],
    method: "Gin, Zitrone und Sirup mit Eis schütteln, in ein Flötenglas abseihen, mit Champagner auffüllen.",
    glass: "Champagnerflöte",
    garnish: "Zitronenzeste",
    history: "Der French 75 wurde nach dem französischen 75-mm-Feldgeschütz aus dem Ersten Weltkrieg benannt, weil sein 'Kick' angeblich ebenso durchschlagend war. Erstmals erwähnt wurde er um 1915, als Vorbild diente er später der berühmten Harry's New York Bar in Paris. Die Kombination aus Gin-Sour und Champagner macht ihn zu einem der elegantesten Drinks der klassischen Cocktailkarte. Bis heute ist er ein beliebter Aperitif- und Feierabend-Cocktail zu festlichen Anlässen.",
    pairsWith: ["Singapore Sling"],
  },
  {
    name: "Singapore Sling",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 30, unit: "ml" },
      { name: "Cherry Heering (Kirschlikör)", amount: 15, unit: "ml" },
      { name: "Cointreau", amount: 7.5, unit: "ml" },
      { name: "DOM Bénédictine", amount: 7.5, unit: "ml" },
      { name: "Vaihinger Ananassaft", amount: 30, unit: "ml" },
      { name: "Limettensaft", amount: 15, unit: "ml" },
      { name: "Giffard Grenadine", amount: 10, unit: "ml" },
      { name: "Angostura Bitters", amount: 1, unit: "dash" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein Glas mit Eiswürfeln abseihen.",
    glass: "Hurricane-Glas oder Longdrinkglas",
    garnish: "Ananasspalte, Cocktailkirsche",
    history: "Der Singapore Sling wurde um 1915 von Barkeeper Ngiam Tong Boon in der Long Bar des Raffles Hotel in Singapur kreiert. Ursprünglich als Damen-Drink gedacht, der wie harmloser Fruchtsaft aussah, tatsächlich aber recht alkoholstark war, wurde er schnell zum Symbol für exotischen Kolonial-Chic. Im Laufe der Jahrzehnte kursierten stark abweichende Rezeptvarianten, bis das Raffles Hotel in den 1970er-Jahren eine offizielle Version festlegte. Heute ist er einer der bekanntesten Signature-Cocktails der Welt.",
    pairsWith: ["French 75"],
  },
  {
    name: "Bee's Knees",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 60, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
      { name: "Giffard Honig-Sirup (1:1)", amount: 20, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Zitronenzeste",
    history: "Der Bee's Knees entstand während der amerikanischen Prohibition (1920–1933), als Honig verwendet wurde, um schlecht destillierten 'Bathtub Gin' erträglicher zu machen. Der Name ist ein damals populärer Slangausdruck für 'das Beste vom Besten'. Die klare Struktur aus Gin, Zitrone und Honig machte ihn zu einem der beliebtesten Sours seiner Zeit. Er diente später auch als direkte Inspiration für moderne Klassiker wie den Gold Rush.",
    pairsWith: ["Gimlet", "Tom Collins", "Aviation"],
  },
  {
    name: "Daiquiri",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 60, unit: "ml" },
      { name: "Limettensaft", amount: 25, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Limettenzeste",
    history: "Der Daiquiri ist nach einer Mine und einem Strand nahe Santiago de Cuba benannt und wurde Ende des 19. Jahrhunderts von amerikanischen Ingenieuren dort kreiert. Weltberühmt wurde er später durch die Bar El Floridita in Havanna und ihren Stammgast Ernest Hemingway. In seiner klassischen, einfachen Form aus nur drei Zutaten gilt er als Musterbeispiel für die Balance zwischen süß, sauer und stark. Aus ihm entwickelten sich unzählige Varianten, vom gefrorenen Frucht-Daiquiri bis zum Hemingway Daiquiri.",
    pairsWith: ["Mojito", "Cuba Libre", "Hemingway Daiquiri"],
  },
  {
    name: "Mojito",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 60, unit: "ml" },
      { name: "Limettensaft", amount: 25, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Minzblätter", amount: 8, unit: "stk" },
      { name: "Schweppes Soda Water (zum Auffüllen)", amount: 30, unit: "ml" },
    ],
    method: "Minze und Limette leicht andrücken, Rum und Sirup zugeben, mit zerstoßenem Eis auffüllen, mit Soda toppen.",
    glass: "Longdrinkglas oder Tumbler",
    garnish: "Minzstrauß",
    history: "Der Mojito stammt aus Kuba, seine Ursprünge werden teils bis ins 16. Jahrhundert zu einem ähnlichen Getränk namens 'El Draque' zurückverfolgt, das mit dem Piraten Sir Francis Drake in Verbindung gebracht wird. In moderner Form etablierte er sich im 20. Jahrhundert in Havannas Bars, allen voran der Bodeguita del Medio. Auch hier soll Ernest Hemingway als prominenter Stammgast zur weltweiten Bekanntheit beigetragen haben. Die Kombination aus frischer Minze, Limette und Rum machte ihn zu einem der meistverkauften Cocktails weltweit.",
    pairsWith: ["Daiquiri", "Cuba Libre", "Hemingway Daiquiri"],
  },
  {
    name: "Piña Colada",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 60, unit: "ml" },
      { name: "Kokoscreme (Coco Lopez)", amount: 30, unit: "ml" },
      { name: "Vaihinger Ananassaft", amount: 90, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis im Blender cremig mixen oder kräftig schütteln.",
    glass: "Hurricane-Glas",
    garnish: "Ananasspalte, Cocktailkirsche",
    history: "Die Piña Colada gilt als Nationalgetränk Puerto Ricos und wurde 1954 von Barkeeper Ramón 'Monchito' Marrero im Caribe Hilton Hotel in San Juan kreiert. Der Durchbruch gelang, als die kurz zuvor erfundene Kokoscreme-Marke Coco Lopez die cremige Textur ermöglichte. Der Name bedeutet übersetzt 'gesiebte Ananas' und bezieht sich auf den frischen Ananassaft als Basiszutat. Sie zählt bis heute zu den bekanntesten Tiki- und Urlaubscocktails der Welt.",
    pairsWith: ["Mai Tai", "Zombie", "Dark 'n' Stormy"],
  },
  {
    name: "Mai Tai",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 30, unit: "ml" },
      { name: "Myer's Rum", amount: 30, unit: "ml" },
      { name: "Orange Curaçao", amount: 15, unit: "ml" },
      { name: "Giffard Orgeat-Sirup (Mandelsirup)", amount: 15, unit: "ml" },
      { name: "Limettensaft", amount: 25, unit: "ml" },
    ],
    method: "Alle Zutaten mit crushed Ice kräftig schütteln und samt Eis in ein Glas geben.",
    glass: "Tumbler oder Tiki-Becher",
    garnish: "Minzzweig, Limettenschale",
    history: "Der Mai Tai wurde 1944 von Victor 'Trader Vic' Bergeron in Oakland, Kalifornien, kreiert, der als Gründungsvater der amerikanischen Tiki-Kultur gilt. Der Legende nach probierte eine tahitianische Freundin den ersten Drink und rief begeistert 'Maita'i roa a'e!', tahitianisch für 'aus dem Reich der Besten' – daher der Name. Über Jahrzehnte stritten sich Trader Vic und sein Konkurrent Don the Beachcomber öffentlich darüber, wer den Drink erfunden hatte. Der Mai Tai gilt bis heute als der Inbegriff des amerikanischen Tiki-Cocktails.",
    pairsWith: ["Piña Colada", "Zombie", "Dark 'n' Stormy"],
  },
  {
    name: "Dark 'n' Stormy",
    basePortions: 1,
    ingredients: [
      { name: "Goslings Black Seal Bermuda Rum", amount: 60, unit: "ml" },
      { name: "Schweppes Ginger Beer (zum Auffüllen)", amount: 120, unit: "ml" },
      { name: "Limettensaft", amount: 10, unit: "ml" },
    ],
    method: "Rum und Limette in ein Glas mit Eis geben, mit Ginger Beer auffüllen und leicht verrühren.",
    glass: "Longdrinkglas",
    garnish: "Limettenspalte",
    history: "Der Dark 'n' Stormy stammt von den Bermudas und ist eng mit der dortigen Rum-Destillerie Gosling's verbunden, deren dunkler Black-Seal-Rum traditionell dafür verwendet wird. Der Name spielt auf die stürmisch-dunklen Wolken über dem Atlantik an, an die die Farbe des Drinks erinnert. Gosling's ließ sich den Namen sogar als eingetragene Marke schützen. Er gilt als Nationalgetränk der Bermudas und international als erfrischender Sommer-Highball.",
    pairsWith: ["Piña Colada", "Mai Tai", "Zombie"],
  },
  {
    name: "Cuba Libre",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 50, unit: "ml" },
      { name: "Cola (zum Auffüllen)", amount: 120, unit: "ml" },
      { name: "Limettensaft", amount: 10, unit: "ml" },
    ],
    method: "Rum und Limette in ein Glas mit Eis geben, mit Cola auffüllen und leicht verrühren.",
    glass: "Longdrinkglas",
    garnish: "Limettenspalte",
    history: "Der Cuba Libre entstand vermutlich kurz nach 1900 in Havanna, als amerikanische Coca-Cola nach Kuba importiert wurde und auf einheimischen Rum traf. Der Name bedeutet 'freies Kuba' und bezieht sich auf den kubanischen Unabhängigkeitskrieg gegen Spanien. Eine bekannte Anekdote erzählt, ein amerikanischer Soldat habe mit dem Drink in der Hand auf 'Cuba libre!' angestoßen. Als simple, wirkungsvolle Kombination aus Rum und Cola gilt er als Urvater unzähliger Rum-Cola-Longdrinks weltweit.",
    pairsWith: ["Daiquiri", "Mojito", "Hemingway Daiquiri"],
  },
  {
    name: "Hemingway Daiquiri",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 60, unit: "ml" },
      { name: "Limettensaft", amount: 20, unit: "ml" },
      { name: "Grapefruitsaft (frisch)", amount: 20, unit: "ml" },
      { name: "Maraschino-Likör", amount: 10, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Limettenzeste",
    history: "Der Hemingway Daiquiri, auch 'Papa Doble' genannt, wurde für den Schriftsteller Ernest Hemingway in seiner Stammbar El Floridita in Havanna kreiert. Da Hemingway unter Diabetes litt, ließ er sich seinen Daiquiri ohne zugesetzten Zucker, dafür mit doppelter Rum-Menge sowie Grapefruit und Maraschino zubereiten. Barkeeper Constantino Ribalaigua Vert perfektionierte diese persönliche Variante, die bald auch andere Gäste bestellten. Sie gilt als eine der bekanntesten literarisch inspirierten Cocktail-Legenden der Barwelt.",
    pairsWith: ["Daiquiri", "Mojito", "Cuba Libre"],
  },
  {
    name: "Zombie",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 30, unit: "ml" },
      { name: "Myer's Rum", amount: 30, unit: "ml" },
      { name: "Smith & Cross Jamaican Overproof Rum", amount: 15, unit: "ml" },
      { name: "Limettensaft", amount: 20, unit: "ml" },
      { name: "Vaihinger Ananassaft", amount: 30, unit: "ml" },
      { name: "Giffard Maracujasirup", amount: 15, unit: "ml" },
      { name: "Zimt-Sirup", amount: 10, unit: "ml" },
      { name: "Angostura Bitters", amount: 1, unit: "dash" },
    ],
    method: "Alle Zutaten mit viel crushed Ice kräftig schütteln und samt Eis in ein Glas geben.",
    glass: "Tiki-Becher oder Hurricane-Glas",
    garnish: "Minzzweig, Ananasblatt",
    history: "Der Zombie wurde in den 1930er-Jahren von Don the Beachcomber in Hollywood erfunden und gilt als einer der Gründungsdrinks der amerikanischen Tiki-Bewegung. Der Legende nach servierte er ihn einem Geschäftsmann als Kater-Notfallmittel vor einer wichtigen Reise, mit angeblich verheerender Wirkung. Um sein Erfolgsrezept geheim zu halten, mischte Don seine Sirupe unter Codenamen und ließ Zutaten in verschlüsselten Flaschen liefern. Wegen seines hohen Alkoholgehalts gilt er bis heute als einer der stärksten klassischen Cocktails.",
    pairsWith: ["Piña Colada", "Mai Tai", "Dark 'n' Stormy"],
  },
  {
    name: "Caipirinha",
    basePortions: 1,
    ingredients: [
      { name: "Nega Fulo", amount: 60, unit: "ml" },
      { name: "Limette (geviertelt)", amount: 1, unit: "stk" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
    ],
    method: "Limette mit Zucker im Glas andrücken, mit Cachaça und crushed Ice auffüllen und verrühren.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Limettenstück",
    history: "Die Caipirinha ist Brasiliens Nationalgetränk, ihre genaue Herkunft liegt im Dunkeln, Theorien reichen von Zuckerrohrplantagen des 19. Jahrhunderts bis zu Hausmitteln gegen die spanische Grippe 1918. Ihr Name leitet sich vom portugiesischen Wort 'caipira' ab, das ursprünglich abwertend für Landbewohner stand. Basis ist Cachaça, ein aus frischem Zuckerrohrsaft destillierter brasilianischer Brand, der sie geschmacklich vom Rum unterscheidet. International wurde sie vor allem durch brasilianische Tourismuswerbung und Fußball-Weltmeisterschaften bekannt.",
    pairsWith: ["Daiquiri", "Mojito", "Cuba Libre"],
  },
  {
    name: "Margarita",
    basePortions: 1,
    ingredients: [
      { name: "Jose Cuervo 100% Agave Tequila", amount: 50, unit: "ml" },
      { name: "Cointreau (Triple Sec)", amount: 20, unit: "ml" },
      { name: "Limettensaft", amount: 20, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein Glas mit Salzrand abseihen.",
    glass: "Margarita-Glas",
    garnish: "Salzrand, Limettenscheibe",
    history: "Über die Herkunft der Margarita kursieren zahlreiche konkurrierende Legenden, von einer texanischen Gastgeberin in den 1940er-Jahren bis zu mexikanischen Bars in Tijuana und Acapulco. Sicher ist, dass sie im Kern eine Tequila-Variante des klassischen 'Daisy'-Cocktails ist, dessen spanische Übersetzung 'Margarita' lautet. Ab den 1970er-Jahren mit der elektrischen Margarita-Maschine explodierte ihre Popularität in den USA. Heute ist sie einer der weltweit meistverkauften Cocktails überhaupt.",
    pairsWith: ["Tommy's Margarita", "Paloma", "Gustavo"],
  },
  {
    name: "Paloma",
    basePortions: 1,
    ingredients: [
      { name: "Jose Cuervo 100% Agave Tequila", amount: 50, unit: "ml" },
      { name: "Grapefruit-Limonade", amount: 100, unit: "ml" },
      { name: "Limettensaft", amount: 10, unit: "ml" },
    ],
    method: "Tequila und Limettensaft in ein Glas mit Eis geben, mit Grapefruit-Limonade auffüllen, leicht verrühren.",
    glass: "Longdrinkglas",
    garnish: "Limettenspalte, Salzrand",
    history: "Die Paloma ist in Mexiko der beliebteste Tequila-Cocktail überhaupt, wird dort weit häufiger konsumiert als die international bekanntere Margarita. Ihr Name bedeutet 'Taube', ihre genaue Herkunft ist nicht dokumentiert, wird aber oft mit Guadalajara in Verbindung gebracht. Die einfache Kombination aus Tequila und spritziger Grapefruit-Limonade macht sie zu einem unkomplizierten Alltagsdrink. Erst in den letzten Jahren fand sie auch international zunehmend Beachtung als leichtere Alternative zur Margarita.",
    pairsWith: ["Margarita", "Tommy's Margarita", "Gustavo"],
  },
  {
    name: "Tequila Sunrise",
    basePortions: 1,
    ingredients: [
      { name: "Jose Cuervo 100% Agave Tequila", amount: 50, unit: "ml" },
      { name: "Vaihinger Orangensaft", amount: 100, unit: "ml" },
      { name: "Giffard Grenadine", amount: 15, unit: "ml" },
    ],
    method: "Tequila und Orangensaft in ein Glas mit Eis geben, Grenadine langsam einsinken lassen.",
    glass: "Longdrinkglas",
    garnish: "Orangenscheibe, Cocktailkirsche",
    history: "Der Tequila Sunrise entstand vermutlich in den 1930er-Jahren in Mexiko, wurde aber erst in den 1970er-Jahren durch eine überarbeitete Version in Kalifornien weltberühmt. Besonders bekannt wurde er, als die Rolling Stones ihn während ihrer US-Tournee 1972 zu ihrem bevorzugten Backstage-Drink erklärten. Der charakteristische Farbverlauf entsteht, weil die schwerere Grenadine langsam im Glas nach unten sinkt und einen Sonnenaufgang-Effekt erzeugt. Er gilt bis heute als einer der optisch eindrucksvollsten Longdrinks überhaupt.",
    pairsWith: ["Oaxaca Old Fashioned", "Espadin Kick"],
  },
  {
    name: "Tommy's Margarita",
    basePortions: 1,
    ingredients: [
      { name: "Jose Cuervo 100% Agave Tequila", amount: 60, unit: "ml" },
      { name: "Limettensaft", amount: 25, unit: "ml" },
      { name: "Agavendicksaft", amount: 15, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein Glas mit Eiswürfeln abseihen.",
    glass: "Tumbler oder Margarita-Glas",
    garnish: "Limettenscheibe",
    history: "Tommy's Margarita wurde in den 1990er-Jahren von Julio Bermejo in seinem Familienrestaurant Tommy's Mexican Restaurant in San Francisco entwickelt. Er ersetzte den üblichen Orangenlikör durch Agavendicksaft, um den reinen Geschmack von 100-Prozent-Agaven-Tequila stärker hervortreten zu lassen. Bermejo gilt zudem als einflussreicher Botschafter für hochwertigen Tequila in den USA. Seine schlankere, weniger süße Rezeptur wird heute von vielen Bartendern gegenüber der klassischen Margarita bevorzugt.",
    pairsWith: ["Margarita", "Paloma", "Gustavo"],
  },
  {
    name: "Oaxaca Old Fashioned",
    basePortions: 1,
    ingredients: [
      { name: "Jose Cuervo 100% Agave Tequila", amount: 45, unit: "ml" },
      { name: "San Cosme Mezcal", amount: 15, unit: "ml" },
      { name: "Agavendicksaft", amount: 7.5, unit: "ml" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
    ],
    method: "Alle Zutaten im Rührglas mit Eis rühren und in ein Glas mit großem Eiswürfel abseihen.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Orangenzeste",
    history: "Der Oaxaca Old Fashioned wurde 2007 vom New Yorker Bartender Phil Ward in der Bar Death & Co entwickelt und gilt als einer der einflussreichsten modernen Agaven-Cocktails. Er überträgt die klassische Old-Fashioned-Struktur auf Tequila und ergänzt sie um einen Schuss rauchigen Mezcal aus der mexikanischen Region Oaxaca. Diese Kombination trug maßgeblich dazu bei, Mezcal in der internationalen Cocktailszene bekannt zu machen. Er gilt heute als Standardrezept für rauchige Agaven-Cocktails in gehobenen Bars weltweit. Eigentlich mit Reposado-Tequila zubereitet, der aktuell nicht im Sortiment geführt wird – hier auf den Blanco-Tequila ausgewichen.",
    pairsWith: ["Tequila Sunrise", "Espadin Kick"],
  },
  {
    name: "Moscow Mule",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 50, unit: "ml" },
      { name: "Limettensaft", amount: 15, unit: "ml" },
      { name: "Schweppes Ginger Beer (zum Auffüllen)", amount: 120, unit: "ml" },
    ],
    method: "Wodka und Limette in einen Kupferbecher mit Eis geben, mit Ginger Beer auffüllen.",
    glass: "Kupferbecher (Mule Mug)",
    garnish: "Limettenspalte, Minzzweig",
    history: "Der Moscow Mule entstand 1941 in Los Angeles, als ein Wodka-Importeur, ein Ginger-Beer-Hersteller und eine Bar-Besitzerin versuchten, ihre schwer verkäuflichen Produkte gemeinsam zu vermarkten. Der markante, verkupferte Becher wurde gezielt als Marketinginstrument eingesetzt, um den Drink unverwechselbar zu machen. Durch geschicktes Foto-Marketing in Bars im ganzen Land trug der Drink maßgeblich dazu bei, Wodka in Amerika überhaupt erst populär zu machen. Er gilt bis heute als der Cocktail, der den amerikanischen Wodka-Boom auslöste.",
    pairsWith: ["Cosmopolitan", "Screwdriver", "Watermelon Man"],
  },
  {
    name: "Cosmopolitan",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 40, unit: "ml" },
      { name: "Cointreau", amount: 15, unit: "ml" },
      { name: "Vaihinger Cranberrysaft", amount: 20, unit: "ml" },
      { name: "Limettensaft", amount: 10, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Orangenzeste",
    history: "Der Cosmopolitan entwickelte sich in den 1980er- und frühen 1990er-Jahren in den USA aus früheren Wodka-Cranberry-Kreationen, wobei mehrere Barkeeper Anspruch auf seine Erfindung erheben. Weltberühmt wurde er vor allem durch die Fernsehserie 'Sex and the City', in der er zum Signature-Drink der Hauptfiguren avancierte. Seine leuchtend rosarote Farbe und die elegante Cocktailschale machten ihn in den 1990er- und 2000er-Jahren zum Inbegriff urbaner Cocktailkultur. Er gilt bis heute als einer der bekanntesten Cocktails der Popkultur. Klassisch mit Zitronen-Vodka zubereitet, der aktuell nicht im Sortiment geführt wird – hier auf den Standard-Vodka ausgewichen.",
    pairsWith: ["Moscow Mule", "Screwdriver", "Watermelon Man"],
  },
  {
    name: "Bloody Mary",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 50, unit: "ml" },
      { name: "Vaihinger Tomatensaft", amount: 100, unit: "ml" },
      { name: "Zitronensaft", amount: 15, unit: "ml" },
      { name: "Worcestersauce", amount: 3, unit: "dash" },
      { name: "Tabasco", amount: 2, unit: "dash" },
    ],
    method: "Alle Zutaten in ein Glas mit Eis geben und verrühren, mit Salz und Pfeffer abschmecken.",
    glass: "Longdrinkglas",
    garnish: "Selleriestange, Zitronenspalte",
    history: "Die Bloody Mary wird oft dem Barkeeper Fernand Petiot zugeschrieben, der in den 1920er-Jahren in der Pariser Harry's New York Bar eine erste Version aus Wodka und Tomatensaft mixte. Später perfektionierte er sie im King Cole Bar des St. Regis Hotels in New York, wo Gewürze wie Worcestersauce und Tabasco hinzukamen. Über die Herkunft des Namens gibt es zahlreiche Theorien, von Königin Maria I. bis zu einer Bar-Bekanntschaft namens Mary. Als deftiger, würziger Drink gilt sie bis heute als der klassische Katerdrink schlechthin.",
  },
  {
    name: "White Russian",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 50, unit: "ml" },
      { name: "Kahlúa", amount: 25, unit: "ml" },
      { name: "Sahne (oder Milch)", amount: 25, unit: "ml" },
    ],
    method: "Wodka und Kaffeelikör in ein Glas mit Eis geben, Sahne vorsichtig darüber schichten.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "ohne",
    history: "Der White Russian ist eine mit Sahne verfeinerte Variante des älteren Black Russian und entstand vermutlich in den 1960er-Jahren; sein genauer Ursprung ist nicht eindeutig belegt. Beide Namen beziehen sich auf Wodka als typisch russische Spirituose, obwohl der Drink selbst amerikanischen Ursprungs ist. Weltweite Popkultur-Berühmtheit erlangte er 1998 durch 'The Big Lebowski', in dem Hauptfigur 'The Dude' den Drink wiederholt konsumiert. Seither gilt er als einer der bekanntesten cremigen Cocktails, oft mit dem Film in Verbindung gebracht.",
    pairsWith: ["Vodka Martini", "Espresso Martini", "Brandy Alexander"],
  },
  {
    name: "Espresso Martini",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 50, unit: "ml" },
      { name: "Kahlúa", amount: 20, unit: "ml" },
      { name: "Frisch gebrühter Espresso", amount: 30, unit: "ml" },
      { name: "Zuckersirup", amount: 10, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis sehr kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Kaffeebohnen",
    history: "Der Espresso Martini wurde in den 1980er-Jahren vom britischen Bartender Dick Bradsell in London erfunden, angeblich auf Bitte eines Models, das einen Drink wollte, der sie 'wach macht und dann betrunken'. Ursprünglich hieß er 'Vodka Espresso', bevor er im Zuge des Martini-Booms der 1990er-Jahre umbenannt wurde. Charakteristisch ist der dichte, haselnussbraune Schaum, der beim kräftigen Schütteln des frischen Espressos entsteht. In den 2010er- und 2020er-Jahren erlebte er weltweit eine zweite, noch größere Welle der Popularität.",
    pairsWith: ["Vodka Martini", "White Russian"],
  },
  {
    name: "Vodka Martini",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 60, unit: "ml" },
      { name: "Martini Dry", amount: 10, unit: "ml" },
    ],
    method: "Im Rührglas mit Eis rühren oder schütteln, in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale (Martini-Glas)",
    garnish: "Olive oder Zitronenzeste",
    history: "Der Vodka Martini entstand als Variante des klassischen Gin-Martini, als Wodka ab den 1950er-Jahren in den USA zunehmend populär wurde. Weltberühmt wurde er vor allem durch die James-Bond-Filme, in denen die Figur ihn stets 'geschüttelt, nicht gerührt' bestellt – ein bewusster Stilbruch gegenüber der klassischen Zubereitung. Puristen argumentieren bis heute, dass Schütteln den Drink unnötig verwässert und trübe macht. Trotzdem gilt der geschüttelte Vodka Martini seit Bond als eine der bekanntesten Cocktail-Bestellungen der Popkultur.",
    pairsWith: ["Martini", "Dirty Martini", "Martinez"],
  },
  {
    name: "Screwdriver",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 50, unit: "ml" },
      { name: "Vaihinger Orangensaft (zum Auffüllen)", amount: 120, unit: "ml" },
    ],
    method: "Wodka in ein Glas mit Eis geben, mit Orangensaft auffüllen und verrühren.",
    glass: "Longdrinkglas",
    garnish: "Orangenscheibe",
    history: "Der Screwdriver entstand vermutlich in den 1940er- oder 1950er-Jahren und wird oft mit amerikanischen Ölarbeitern im Nahen Osten in Verbindung gebracht, die ihren Wodka angeblich mit einem Schraubenzieher im Orangensaft verrührten. Als eine der einfachsten denkbaren Cocktail-Kombinationen trug er maßgeblich dazu bei, Wodka in den USA und Europa alltagstauglich zu machen. Seine schlichte Zubereitung machte ihn schnell zum Standard-Drink in Bars und Privathaushalten. Er gilt bis heute als Einstiegsdrink für viele, die zum ersten Mal selbst Cocktails mixen.",
    pairsWith: ["Moscow Mule", "Cosmopolitan", "Watermelon Man"],
  },
  {
    name: "Sidecar",
    basePortions: 1,
    ingredients: [
      { name: "Hennessy V.S.", amount: 50, unit: "ml" },
      { name: "Cointreau", amount: 20, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes, mit Zucker gerändertes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Zuckerrand, Orangenzeste",
    history: "Der Sidecar entstand vermutlich kurz nach dem Ersten Weltkrieg in Paris oder London, wobei sowohl die Ritz Bar in Paris als auch Harry's New York Bar seine Erfindung für sich beanspruchen. Der Name soll sich auf den Beiwagen eines Motorrads beziehen, in dem angeblich ein Gast zur Bar kutschiert wurde. Als eine der ersten großen Cognac-Cocktail-Kreationen der 1920er-Jahre setzte er den Grundstein für die spätere 'Sour mit Triple Sec'-Formel, die auch bei Margarita oder White Lady wiederkehrt. Er gilt bis heute als der elegante Klassiker unter den Brandy-Cocktails.",
    pairsWith: ["Brandy Alexander", "French Connection", "Vieux Carré"],
  },
  {
    name: "Brandy Alexander",
    basePortions: 1,
    ingredients: [
      { name: "Hennessy V.S.", amount: 30, unit: "ml" },
      { name: "Giffard Crème de Cacao White", amount: 15, unit: "ml" },
      { name: "Giffard Crème de Cacao Brown", amount: 15, unit: "ml" },
      { name: "Sahne", amount: 30, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "Geriebene Muskatnuss",
    history: "Der Brandy Alexander ist eine Weiterentwicklung des älteren, gin-basierten 'Alexander' und wurde vermutlich in den 1920er-Jahren durch das Ersetzen von Gin mit Cognac populär. Mit seiner cremigen, dessertartigen Textur aus Sahne und Kakaolikör gilt er eher als flüssiger Nachtisch denn als klassischer Aperitif. Manche Quellen bringen seine Erfindung mit einer New Yorker Hochzeitsfeier in Verbindung, belegt ist dies jedoch nicht eindeutig. Er ist bis heute ein beliebter After-Dinner-Drink für Liebhaber süßer, cremiger Cocktails.",
    pairsWith: ["Sidecar", "French Connection", "Vieux Carré"],
  },
  {
    name: "French Connection",
    basePortions: 1,
    ingredients: [
      { name: "Hennessy V.S.", amount: 40, unit: "ml" },
      { name: "Amaretto", amount: 20, unit: "ml" },
    ],
    method: "Beide Zutaten in ein Glas mit Eis geben und verrühren.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "ohne",
    history: "Der French Connection ist nach dem gleichnamigen, oscarprämierten Kriminalfilm von 1971 benannt, der von einem Drogenschmuggel-Ring zwischen Frankreich und den USA handelt. Als Zwei-Zutaten-Kombination aus französischem Cognac und italienischem Mandellikör verbindet er zwei europäische Spirituosen-Traditionen. Seine unkomplizierte Zubereitung ohne Shaker machte ihn zu einem beliebten, leicht zu mixenden After-Dinner-Drink der 1970er-Jahre. Er wird bis heute vor allem wegen seiner warmen, mandelig-fruchtigen Cognac-Note geschätzt.",
    pairsWith: ["Sidecar", "Brandy Alexander", "Vieux Carré"],
  },
  {
    name: "Bellini",
    basePortions: 1,
    ingredients: [
      { name: "Weißer Pfirsichpüree", amount: 50, unit: "ml" },
      { name: "Chapeau Secco (zum Auffüllen)", amount: 75, unit: "ml" },
    ],
    method: "Pfirsichpüree in ein Glas geben und vorsichtig mit Prosecco auffüllen.",
    glass: "Champagnerflöte",
    garnish: "ohne",
    history: "Der Bellini wurde in den 1930er- oder 1940er-Jahren von Giuseppe Cipriani, dem Gründer der berühmten Harry's Bar in Venedig, erfunden. Benannt ist er nach dem venezianischen Renaissance-Maler Giovanni Bellini, dessen Gemälde häufig ähnliche zart-rosa Farbtöne zeigten. Ursprünglich wurde er nur im Sommer serviert, wenn frische weiße Pfirsiche aus der Region verfügbar waren. Heute zählt er neben dem Martini zu den bekanntesten Aperitif-Cocktails der Welt.",
    pairsWith: ["Aperol Spritz", "Americano", "Negroni Sbagliato"],
  },
  {
    name: "Mimosa",
    basePortions: 1,
    ingredients: [
      { name: "Vaihinger Orangensaft", amount: 60, unit: "ml" },
      { name: "Taittinger Brut Réserve (zum Auffüllen)", amount: 90, unit: "ml" },
    ],
    method: "Orangensaft in ein Glas geben und vorsichtig mit Champagner auffüllen.",
    glass: "Champagnerflöte",
    garnish: "Orangenzeste",
    history: "Der Mimosa entstand in den 1920er-Jahren, vermutlich im Ritz Hotel in Paris, als einfache Kombination aus Champagner und Orangensaft. Sein Name bezieht sich auf die gelbblühende Mimosenpflanze, deren Farbe an den hellen Orangenton des Drinks erinnert. In den USA wurde er später vor allem als fester Bestandteil des klassischen Sonntags-Brunchs populär. Heute gilt er als Inbegriff des leichten, festlichen Sekt-Cocktails zu jeder Tageszeit.",
    pairsWith: ["Aperol Spritz", "Americano", "Negroni Sbagliato"],
  },
  {
    name: "Aperol Spritz",
    basePortions: 1,
    ingredients: [
      { name: "Aperol", amount: 60, unit: "ml" },
      { name: "Chapeau Secco", amount: 90, unit: "ml" },
      { name: "Schweppes Soda Water", amount: 30, unit: "ml" },
    ],
    method: "Alle Zutaten in ein Glas mit Eis geben und vorsichtig verrühren.",
    glass: "Weinglas (Ballonglas)",
    garnish: "Orangenscheibe",
    history: "Der Aperol Spritz hat seine Wurzeln im norditalienischen 'Spritz', der im 19. Jahrhundert entstand, als österreichische Soldaten in Venetien ihren Wein mit Sodawasser 'spritzten', um ihn milder zu machen. Die moderne, Aperol-basierte Version etablierte sich vor allem ab den 2000er-Jahren als beliebter Aperitif im Veneto. Durch geschicktes internationales Marketing der Marke Aperol wurde der Drink innerhalb weniger Jahre zum globalen Sommerphänomen. Heute zählt er zu den meistverkauften Aperitif-Cocktails weltweit.",
    pairsWith: ["Americano", "Negroni Sbagliato", "Beery Negroni Sbagliato"],
  },
  {
    name: "Americano",
    basePortions: 1,
    ingredients: [
      { name: "Campari", amount: 30, unit: "ml" },
      { name: "Antica Formula", amount: 30, unit: "ml" },
      { name: "Schweppes Soda Water (zum Auffüllen)", amount: 30, unit: "ml" },
    ],
    method: "Campari und Wermut in ein Glas mit Eis geben, mit Soda auffüllen und verrühren.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Orangenscheibe",
    history: "Der Americano entstand um 1860 in Mailand als 'Milano-Torino', benannt nach den Herkunftsstädten von Campari und Wermut. Seinen heutigen Namen erhielt er, weil er bei amerikanischen Touristen in Italien besonders beliebt war. Er gilt zudem als direkter Vorläufer des Negroni, der entstand, als jemand ihm zusätzlich Gin hinzufügte. Als leichter, spritziger Aperitif mit niedrigerem Alkoholgehalt ist er bis heute in italienischen Bars fest etabliert.",
    pairsWith: ["Aperol Spritz", "Negroni Sbagliato", "Beery Negroni Sbagliato"],
  },
  {
    name: "Negroni Sbagliato",
    basePortions: 1,
    ingredients: [
      { name: "Antica Formula", amount: 30, unit: "ml" },
      { name: "Campari", amount: 30, unit: "ml" },
      { name: "Chapeau Secco (zum Auffüllen)", amount: 30, unit: "ml" },
    ],
    method: "Wermut und Campari in ein Glas mit Eis geben, mit Prosecco auffüllen und leicht verrühren.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Orangenscheibe",
    history: "Der Negroni Sbagliato entstand der Legende nach in den 1970er-Jahren in der Mailänder Bar Basso, als ein Barkeeper aus Versehen ('sbagliato' heißt 'falsch gemacht') Prosecco statt Gin in einen Negroni goss. Statt den Fehler zu korrigieren, wurde der leichtere Zufallsdrink beibehalten und zu einem eigenständigen Klassiker. Jahrzehntelang blieb er vor allem in Italien bekannt, bevor er 2022 durch ein virales Video mit Schauspielerin Emma D'Arcy weltweit zum Social-Media-Trend wurde. Heute gilt er als leichtere, prickelnde Alternative zum klassischen Negroni.",
    pairsWith: ["Aperol Spritz", "Americano", "Beery Negroni Sbagliato"],
  },
  {
    name: "Long Island Iced Tea",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 15, unit: "ml" },
      { name: "Bombay Sapphire Gin", amount: 15, unit: "ml" },
      { name: "Havana Club 3 Años", amount: 15, unit: "ml" },
      { name: "Jose Cuervo 100% Agave Tequila", amount: 15, unit: "ml" },
      { name: "Cointreau", amount: 15, unit: "ml" },
      { name: "Zitronensaft", amount: 25, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Cola (zum Auffüllen)", amount: 30, unit: "ml" },
    ],
    method: "Alle Spirituosen, Zitrone und Sirup mit Eis schütteln, in ein Glas mit Eis abseihen, mit Cola auffüllen.",
    glass: "Longdrinkglas",
    garnish: "Zitronenscheibe",
    history: "Der Long Island Iced Tea entstand vermutlich in den 1970er-Jahren auf Long Island im US-Bundesstaat New York, wobei mehrere Barkeeper konkurrierende Erfindungsgeschichten erzählen. Seine Mischung aus vier bis fünf klaren Spirituosen ergibt zusammen mit Cola eine Optik, die täuschend echtem Eistee ähnelt – daher der Name. Trotz seines vergleichsweise milden Geschmacks gehört er wegen der Kombination mehrerer hochprozentiger Spirituosen zu den stärksten weit verbreiteten Cocktails. Er ist bis heute vor allem als Partydrink für ausgelassene Abende bekannt.",
    pairsWith: ["Suffering Bastard", "Zombie"],
  },
  {
    name: "Grasshopper",
    basePortions: 1,
    ingredients: [
      { name: "Grüner Crème de Menthe", amount: 30, unit: "ml" },
      { name: "Giffard Crème de Cacao White", amount: 30, unit: "ml" },
      { name: "Sahne", amount: 30, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein gekühltes Cocktailglas abseihen.",
    glass: "Cocktailschale",
    garnish: "ohne",
    history: "Der Grasshopper wurde 1918 von Philibert Guichet im Tujague's Restaurant in New Orleans anlässlich eines Cocktail-Wettbewerbs erfunden, den er damit gewann. Seinen Namen und seine leuchtend grüne Farbe verdankt er dem verwendeten grünen Pfefferminzlikör. Mit seiner cremigen, dessertartigen Textur gilt er eher als flüssiger Nachtisch denn als klassischer Aperitif-Cocktail. Er zählt bis heute zu den bekanntesten süßen After-Dinner-Drinks der amerikanischen Cocktailgeschichte.",
    pairsWith: ["White Russian", "Brandy Alexander", "Amaretto Sour"],
  },
  {
    name: "Amaretto Sour",
    basePortions: 1,
    ingredients: [
      { name: "Amaretto", amount: 60, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
      { name: "Zuckersirup", amount: 10, unit: "ml" },
      { name: "Eiweiß", amount: 20, unit: "ml" },
    ],
    method: "Alle Zutaten mit Eis kräftig schütteln und in ein Glas mit Eiswürfeln abseihen.",
    glass: "Tumbler (Old Fashioned Glas)",
    garnish: "Orangenscheibe, Cocktailkirsche",
    history: "Der Amaretto Sour übertrug ab den 1970er-Jahren das klassische Sour-Prinzip aus Spirituose, Zitrussaft und Zucker auf den italienischen Mandellikör Amaretto. Mit dem internationalen Erfolg der Marke Disaronno wurde er in den 1970er- und 1980er-Jahren zu einem der meistbestellten Cocktails in Bars. Sein süßlich-nussiges Aroma machte ihn besonders bei Cocktail-Einsteigern beliebt. In den letzten Jahren erlebt er, oft mit Eiweiß für mehr Textur zubereitet, eine Renaissance in der Craft-Cocktail-Szene.",
    pairsWith: ["White Russian", "Brandy Alexander", "Grasshopper"],
  },
];
