// Eigene Rezepte der Bar, vom Nutzer aus der internen Rezeptmappe übernommen.
// Diese Bibliothek hat Vorrang vor den generischen Klassikern (js/classicsData.js) –
// ein gleichnamiges Rezept hier überschreibt den generischen Klassiker.
export const HOUSE_RECIPES = [
  {
    name: "Himbeer-Ingwer Fizz",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Gin", amount: 45, unit: "ml" },
      { name: "Himbeer-Sirup", amount: 25, unit: "ml" },
      { name: "Zitronensaft", amount: 25, unit: "ml" },
      { name: "Eiweiß", amount: 15, unit: "ml" },
      { name: "Ginger Beer (zum Auffüllen, 100–120 ml)", amount: 110, unit: "ml" },
    ],
    method: "Shake – Strain – Fill Up",
    glass: "Longdrinkglas",
    garnish: "Zeste",
    ice: "Würfel",
  },
  {
    name: "Mai Tai 1947",
    basePortions: 1,
    ingredients: [
      { name: "Matusalem Rum 15yo", amount: 35, unit: "ml" },
      { name: "Smith & Cross Rum", amount: 35, unit: "ml" },
      { name: "Grand Marnier", amount: 15, unit: "ml" },
      { name: "Mandelsirup (Orgeat)", amount: 15, unit: "ml" },
      { name: "Limette", amount: 25, unit: "ml" },
    ],
    method: "Shake, Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze, Limettenrad, Kirsche",
    ice: "Crushed Eis",
  },
  {
    name: "Martinez",
    basePortions: 1,
    ingredients: [
      { name: "Bene Dry Gin", amount: 35, unit: "ml" },
      { name: "Antica Formula", amount: 35, unit: "ml" },
      { name: "?? – Zutat bitte ergänzen (auf der Vorlage nur \"5ml,\" ohne Namen)", amount: 5, unit: "ml" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
    ],
    method: "Stir & Strain",
    glass: "V-Form-Glas (Coupette)",
    garnish: "Orangenzeste (Tisch-Service)",
    ice: "Würfel",
  },
  {
    name: "Monkey Island",
    basePortions: 1,
    ingredients: [
      { name: "Banane", amount: 1, unit: "stk" },
      { name: "Milch", amount: 150, unit: "ml" },
      { name: "Sahne", amount: 35, unit: "ml" },
      { name: "Vanille-Sirup", amount: 15, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "Schokosoße ins Glas",
    ice: "–",
  },
  {
    name: "Morgentau",
    basePortions: 1,
    ingredients: [
      { name: "Morgentau Tee", amount: 50, unit: "ml" },
      { name: "Yuzu", amount: 30, unit: "ml" },
      { name: "Martini Florale", amount: 30, unit: "ml" },
      { name: "Zitrone", amount: 30, unit: "ml" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (DOF)",
    garnish: "Limettenrad, Minze",
    ice: "Würfel",
  },
  {
    name: "Mystic Treasure",
    basePortions: 1,
    ingredients: [
      { name: "Gosling's Rum", amount: 45, unit: "ml" },
      { name: "Vanille-Sirup", amount: 15, unit: "ml" },
      { name: "Limette", amount: 20, unit: "ml" },
      { name: "Mystic Mango (zum Auffüllen, 120–150 ml)", amount: 135, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Limette, Minze",
    ice: "Würfel",
  },
  {
    name: "Orange & Thymian Gimlet",
    basePortions: 1,
    ingredients: [
      { name: "Tanqueray Sevilla", amount: 45, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Säure-Mischung", amount: 20, unit: "ml" },
      { name: "Thymian (wenig)", amount: 1, unit: "stk" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (SOF)",
    garnish: "Thymian und Schleierkraut in Dry Orange stecken",
    ice: "Würfel",
  },
  {
    name: "Pisco Punch",
    basePortions: 1,
    ingredients: [
      { name: "Pisco", amount: 60, unit: "ml" },
      { name: "Limette", amount: 30, unit: "ml" },
      { name: "Ananas-Oleo-Saccharum", amount: 30, unit: "ml" },
    ],
    method: "Shake & Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze und Limette",
    ice: "Crushed Ice",
  },
  {
    name: "Rhubarb Rosato",
    basePortions: 1,
    ingredients: [
      { name: "Ramazzotti Rosato", amount: 45, unit: "ml" },
      { name: "Fritz Rhabarber Schorle", amount: 100, unit: "ml" },
      { name: "Schweppes Dry Tonic", amount: 100, unit: "ml" },
      { name: "Basilikumblätter", amount: 5, unit: "stk" },
    ],
    method: "Build in Glas",
    glass: "Weinglas",
    garnish: "Basilikumblatt",
    ice: "Würfel",
  },
  {
    name: "Sea Breeze",
    basePortions: 1,
    ingredients: [
      { name: "Helbing Kümmel", amount: 50, unit: "ml" },
      { name: "Apfelsaft", amount: 50, unit: "ml" },
      { name: "Citrus-Säure", amount: 12, unit: "ml" },
      { name: "Thomas Henry Pink Grapefruit (Menge auf Vorlage nicht angegeben, bitte prüfen)", amount: 100, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Tumbler (DOF)",
    garnish: "Minze, Dry Grapefruit",
    ice: "Würfel",
  },
  {
    name: "Sloppy Joe Mojito",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3", amount: 45, unit: "ml" },
      { name: "Limettensaft", amount: 25, unit: "ml" },
      { name: "Grenadine", amount: 20, unit: "ml" },
      { name: "Minzblätter (10–15)", amount: 12, unit: "stk" },
      { name: "Soda (zum Auffüllen, 80–100 ml)", amount: 90, unit: "ml" },
    ],
    method: "Build / Muddeln / Fill Up",
    glass: "Longdrinkglas",
    garnish: "Minze, Dry Limette",
    ice: "Wenig Würfel und Crushed Ice",
  },
  {
    name: "Suffering Bastard",
    basePortions: 1,
    ingredients: [
      { name: "Bulleit Bourbon", amount: 25, unit: "ml" },
      { name: "Bombay Gin", amount: 30, unit: "ml" },
      { name: "Limette", amount: 15, unit: "ml" },
      { name: "Orange (halb, ausgepresst)", amount: 0.5, unit: "stk" },
      { name: "Bitter", amount: 2, unit: "dash" },
      { name: "Ginger Beer (Menge auf Vorlage nicht angegeben, bitte prüfen)", amount: 100, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Minze, Dry Fruit",
    ice: "Würfel",
  },
  {
    name: "Tea Break",
    basePortions: 1,
    ingredients: [
      { name: "Pfirsich Eistee", amount: 20, unit: "ml" },
      { name: "Bergamotte", amount: 30, unit: "ml" },
      { name: "Earl Grey Tee", amount: 50, unit: "ml" },
      { name: "Zuckersirup", amount: 20, unit: "ml" },
    ],
    method: "Muddeln, Shake, Fine Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze, Ingwer",
    ice: "Würfel",
  },
  {
    name: "Vieux Carré",
    basePortions: 1,
    ingredients: [
      { name: "Sazerac Rye", amount: 35, unit: "ml" },
      { name: "Hennessy VSOP", amount: 35, unit: "ml" },
      { name: "Antica Formula", amount: 20, unit: "ml" },
      { name: "DOM Bénédictine", amount: 10, unit: "ml" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
    ],
    method: "Stir & Strain",
    glass: "Nick & Nora",
    garnish: "Orangenzeste",
    ice: "–",
  },
  {
    name: "Watermelon Man",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 40, unit: "ml" },
      { name: "Monin Melone-Sirup", amount: 30, unit: "ml" },
      { name: "Zitrone", amount: 25, unit: "ml" },
      { name: "Minzblätter (8–10)", amount: 9, unit: "stk" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze",
    ice: "Crushed Eis",
  },
  {
    name: "Asian Moskito",
    basePortions: 1,
    ingredients: [
      { name: "Minzblätter", amount: 10, unit: "stk" },
      { name: "Limettenblätter", amount: 3, unit: "stk" },
      { name: "Kalamansi-Püree", amount: 40, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Bitter Lemon (zum Auffüllen)", amount: 140, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Limettenblätter, Minze",
    ice: "Eiswürfel",
  },
  {
    name: "Asian Mule",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 45, unit: "ml" },
      { name: "Minzblätter", amount: 10, unit: "stk" },
      { name: "Limettenblätter", amount: 3, unit: "stk" },
      { name: "Kalamansi-Püree", amount: 20, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Ginger Beer (zum Auffüllen)", amount: 120, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Limettenblätter, Minze",
    ice: "Würfel",
  },
  {
    name: "Aviation",
    basePortions: 1,
    ingredients: [
      { name: "Tanqueray Gin", amount: 45, unit: "ml" },
      { name: "Crème de Violette", amount: 10, unit: "ml" },
      { name: "Maraschino-Likör", amount: 10, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
    ],
    method: "Shake, Fine Strain",
    glass: "V-Form-Glas",
    garnish: "Zitronenzeste",
    ice: "–",
  },
  {
    name: "Basil Cooler",
    basePortions: 1,
    ingredients: [
      { name: "Basilikumblätter (5–6)", amount: 5, unit: "stk" },
      { name: "Pfirsich Eistee", amount: 30, unit: "ml" },
      { name: "Zuckersirup", amount: 10, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
      { name: "The Basil Limo (zum Auffüllen)", amount: 150, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Basilikumblatt",
    ice: "Würfel",
  },
  {
    name: "Bee's Knees Niece",
    basePortions: 1,
    ingredients: [
      { name: "Earl-Grey-infused Bombay Gin", amount: 50, unit: "ml" },
      { name: "Honig-Sirup", amount: 25, unit: "ml" },
      { name: "Boiron Bergamotte-Püree", amount: 30, unit: "ml" },
      { name: "Zitrone", amount: 10, unit: "ml" },
    ],
    method: "Shake, Fine Strain",
    glass: "Coupette",
    garnish: "Zeste oder Limettenrad",
    ice: "",
  },
  {
    name: "Beery Negroni Sbagliato",
    basePortions: 1,
    ingredients: [
      { name: "Beery Campari-Vermouth-Mix", amount: 70, unit: "ml" },
      { name: "A-Rosa Sekt", amount: 70, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Tumbler (DOF)",
    garnish: "Dry/Fresh Orange, TK Beeren",
    ice: "Würfel",
  },
  {
    name: "Captain Blaubär",
    basePortions: 1,
    ingredients: [
      { name: "Blaubeerenpüree", amount: 70, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
      { name: "Bananensaft", amount: 70, unit: "ml" },
      { name: "Blue Curaçao Sirup", amount: 10, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "–",
  },
  {
    name: "Cosmo 1934",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Gin", amount: 50, unit: "ml" },
      { name: "Himbeersirup", amount: 25, unit: "ml" },
      { name: "Zitronensaft", amount: 30, unit: "ml" },
      { name: "Eiweiß", amount: 15, unit: "ml" },
      { name: "Weißer Wermut", amount: 10, unit: "ml" },
      { name: "Cointreau", amount: 10, unit: "ml" },
    ],
    method: "Shaken und Strain",
    glass: "Coupette",
    garnish: "",
    ice: "–",
  },
  {
    name: "Cream Berry",
    basePortions: 1,
    ingredients: [{ name: "Pre-Mix", amount: 100, unit: "ml" }],
    method: "Stir auf Würfel oder Block",
    glass: "Tumbler (DOF)",
    garnish: "Espuma",
    ice: "Würfel",
  },
  {
    name: "Cucumber Elderflower Collins",
    basePortions: 1,
    ingredients: [
      { name: "Tanqueray 0,0% Gin", amount: 45, unit: "ml" },
      { name: "Holunderblütensirup", amount: 20, unit: "ml" },
      { name: "Zitrone", amount: 25, unit: "ml" },
      { name: "Gurkenscheiben (2–3, muddeln)", amount: 2, unit: "stk" },
      { name: "Soda (zum Auffüllen)", amount: 120, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Zitronenscheibe oder Zeste",
    ice: "Würfel",
  },
  {
    name: "Der Grinch",
    basePortions: 1,
    ingredients: [
      { name: "Apfelsaft", amount: 100, unit: "ml" },
      { name: "Apfelsirup", amount: 35, unit: "ml" },
      { name: "Kiwi-Püree", amount: 40, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "–",
  },
  {
    name: "Espadin Kick",
    basePortions: 1,
    ingredients: [
      { name: "San Cosme Mezcal", amount: 50, unit: "ml" },
      { name: "Limette", amount: 25, unit: "ml" },
      { name: "Agavensirup", amount: 20, unit: "ml" },
      { name: "Kardamomkapseln", amount: 3, unit: "stk" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (SOF)",
    garnish: "Absinth-Spray und Limettenzeste",
    ice: "Block",
  },
  {
    name: "Frozen KIBA",
    basePortions: 1,
    ingredients: [
      { name: "Banane", amount: 1, unit: "stk" },
      { name: "Bananensaft", amount: 70, unit: "ml" },
      { name: "Kirschsaft", amount: 50, unit: "ml" },
      { name: "Sahne", amount: 30, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "–",
  },
  {
    name: "Fruit of the Loom",
    basePortions: 1,
    ingredients: [
      { name: "Mango-Püree", amount: 35, unit: "ml" },
      { name: "Erdbeer-Püree", amount: 35, unit: "ml" },
      { name: "Zitrone", amount: 15, unit: "ml" },
      { name: "Vanille-Sirup", amount: 10, unit: "ml" },
      { name: "Ananassaft", amount: 70, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "Crushed Ice",
  },
  {
    name: "Gustavo",
    basePortions: 1,
    ingredients: [
      { name: "Jose Cuervo Tequila", amount: 45, unit: "ml" },
      { name: "Hibiskus-Sirup", amount: 15, unit: "ml" },
      { name: "Limette", amount: 20, unit: "ml" },
      { name: "Thomas Henry Pink Grapefruit (zum Auffüllen, 120–140 ml)", amount: 130, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Salzrand, Dry Grapefruit",
    ice: "Würfel",
  },
  {
    name: "Inspired by Snickers",
    basePortions: 1,
    ingredients: [{ name: "Pre-Mix", amount: 80, unit: "ml" }],
    method: "Stir & Strain",
    glass: "Tumbler (SOF)",
    garnish: "Gewürfelter Snickers",
    ice: "Block",
  },
];
