// Eigene Rezepte der Bar, vom Nutzer aus der internen Rezeptmappe übernommen.
// Diese Bibliothek hat Vorrang vor den generischen Klassikern (js/classicsData.js) –
// ein gleichnamiges Rezept hier überschreibt den generischen Klassiker.
//
// Zutatennamen sind auf die tatsächlich geführten Produkte aus productsData.js gemappt
// (mit dem Barbesitzer abgestimmt), damit Aromenmatrix/Verkaufsmatrix/Empfehlungssystem
// die Rezepte korrekt zuordnen können. Frische Zutaten (Limette, Minze, Zitrone etc.)
// bleiben bewusst generisch, da sie nicht als Katalogprodukt geführt werden.
export const HOUSE_RECIPES = [
  {
    name: "Himbeer-Ingwer Fizz",
    category: "Gin",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 45, unit: "ml" },
      { name: "Giffard Himbeersirup", amount: 25, unit: "ml" },
      { name: "Zitronensaft", amount: 25, unit: "ml" },
      { name: "Eiweiß", amount: 15, unit: "ml" },
      { name: "Schweppes Ginger Beer (zum Auffüllen, 100–120 ml)", amount: 110, unit: "ml" },
    ],
    method: "Shake – Strain – Fill Up",
    glass: "Longdrinkglas",
    garnish: "Zeste",
    ice: "Würfel",
    pairsWith: ["Gimlet", "Tom Collins", "Aviation"],
  },
  {
    name: "Mai Tai 1947",
    category: "Rum & Cachaça",
    basePortions: 1,
    ingredients: [
      { name: "Matusalem 15 Y.O.", amount: 35, unit: "ml" },
      { name: "Smith & Cross Jamaican Overproof Rum", amount: 35, unit: "ml" },
      { name: "Grand Marnier", amount: 15, unit: "ml" },
      { name: "Giffard Orgeat-Sirup (Mandelsirup)", amount: 15, unit: "ml" },
      { name: "Limette", amount: 25, unit: "ml" },
    ],
    method: "Shake, Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze, Limettenrad, Kirsche",
    ice: "Crushed Eis",
    pairsWith: ["Piña Colada", "Mai Tai", "Zombie"],
  },
  {
    name: "Martinez",
    category: "Gin",
    basePortions: 1,
    ingredients: [
      { name: "Bene Dry Gin", amount: 35, unit: "ml" },
      { name: "Antica Formula", amount: 35, unit: "ml" },
      { name: "Maraschino-Likör", amount: 5, unit: "ml" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
    ],
    method: "Stir & Strain",
    glass: "V-Form-Glas (Coupette)",
    garnish: "Orangenzeste (Tisch-Service)",
    ice: "Würfel",
    pairsWith: ["Martini", "Dirty Martini", "Negroni"],
  },
  {
    name: "Monkey Island",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Banane", amount: 1, unit: "stk" },
      { name: "Milch", amount: 150, unit: "ml" },
      { name: "Sahne", amount: 35, unit: "ml" },
      { name: "Giffard Vanille-Sirup", amount: 15, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "Schokosoße ins Glas",
    ice: "–",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Der Grinch"],
  },
  {
    name: "Morgentau",
    category: "Aperitivo & Spritz",
    basePortions: 1,
    ingredients: [
      { name: "Ronnefeldt Morgentau", amount: 50, unit: "ml" },
      { name: "Monin Yuzu-Sirup", amount: 30, unit: "ml" },
      { name: "Martini Florale", amount: 30, unit: "ml" },
      { name: "Zitrone", amount: 30, unit: "ml" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (DOF)",
    garnish: "Limettenrad, Minze",
    ice: "Würfel",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Der Grinch"],
  },
  {
    name: "Mystic Treasure",
    category: "Rum & Cachaça",
    basePortions: 1,
    ingredients: [
      { name: "Goslings Black Seal Bermuda Rum", amount: 45, unit: "ml" },
      { name: "Giffard Vanille-Sirup", amount: 15, unit: "ml" },
      { name: "Limette", amount: 20, unit: "ml" },
      { name: "Thomas Henry Mystic Mango (zum Auffüllen, 120–150 ml)", amount: 135, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Limette, Minze",
    ice: "Würfel",
    pairsWith: ["Piña Colada", "Mai Tai", "Zombie"],
  },
  {
    name: "Orange & Thymian Gimlet",
    category: "Gin",
    basePortions: 1,
    ingredients: [
      { name: "Tanqueray Flor de Sevilla", amount: 45, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Säure-Mischung", amount: 20, unit: "ml" },
      { name: "Thymian (wenig)", amount: 1, unit: "stk" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (SOF)",
    garnish: "Thymian und Schleierkraut in Dry Orange stecken",
    ice: "Würfel",
    pairsWith: ["Gimlet", "Tom Collins", "Aviation"],
  },
  {
    name: "Pisco Punch",
    category: "Brände",
    basePortions: 1,
    ingredients: [
      { name: "Pisco", amount: 60, unit: "ml" },
      { name: "Limette", amount: 30, unit: "ml" },
      { name: "Ananas-Oleo-Saccharum", amount: 30, unit: "ml" },
    ],
    method: "Shake & Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze und Limette",
    ice: "Crushed Ice",
    pairsWith: ["Sidecar", "Brandy Alexander", "French Connection"],
  },
  {
    name: "Rhubarb Rosato",
    category: "Aperitivo & Spritz",
    basePortions: 1,
    ingredients: [
      { name: "Ramazzotti Rosato", amount: 45, unit: "ml" },
      { name: "Fritz-Spritz Bio-Rhabarber", amount: 100, unit: "ml" },
      { name: "Schweppes Dry Tonic Water", amount: 100, unit: "ml" },
      { name: "Basilikumblätter", amount: 5, unit: "stk" },
    ],
    method: "Build in Glas",
    glass: "Weinglas",
    garnish: "Basilikumblatt",
    ice: "Würfel",
    pairsWith: ["Aperol Spritz", "Americano", "Negroni Sbagliato"],
  },
  {
    name: "Sea Breeze",
    category: "Liköre & Amaro",
    basePortions: 1,
    ingredients: [
      { name: "Helbing Kümmel", amount: 50, unit: "ml" },
      { name: "Vaihinger Apfelsaft", amount: 50, unit: "ml" },
      { name: "Citrus-Säure", amount: 12, unit: "ml" },
      { name: "Thomas Henry Pink Grapefruit (zum Auffüllen)", amount: 150, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Tumbler (DOF)",
    garnish: "Minze, Dry Grapefruit",
    ice: "Würfel",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Der Grinch"],
  },
  {
    name: "Sloppy Joe Mojito",
    category: "Rum & Cachaça",
    basePortions: 1,
    ingredients: [
      { name: "Havana Club 3 Años", amount: 45, unit: "ml" },
      { name: "Limettensaft", amount: 25, unit: "ml" },
      { name: "Giffard Grenadine", amount: 20, unit: "ml" },
      { name: "Minzblätter (10–15)", amount: 12, unit: "stk" },
      { name: "Schweppes Soda Water (zum Auffüllen, 80–100 ml)", amount: 90, unit: "ml" },
    ],
    method: "Build / Muddeln / Fill Up",
    glass: "Longdrinkglas",
    garnish: "Minze, Dry Limette",
    ice: "Wenig Würfel und Crushed Ice",
    pairsWith: ["Daiquiri", "Mojito", "Cuba Libre"],
  },
  {
    name: "Suffering Bastard",
    category: "Gin",
    basePortions: 1,
    ingredients: [
      { name: "Bulleit Bourbon", amount: 25, unit: "ml" },
      { name: "Bombay Sapphire Gin", amount: 30, unit: "ml" },
      { name: "Limette", amount: 15, unit: "ml" },
      { name: "Orange (halb, ausgepresst)", amount: 0.5, unit: "stk" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
      { name: "Schweppes Ginger Beer (zum Auffüllen)", amount: 150, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Minze, Dry Fruit",
    ice: "Würfel",
    pairsWith: ["Long Island Iced Tea", "Zombie"],
  },
  {
    name: "Tea Break",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Rauch Eistee Pfirsich", amount: 20, unit: "ml" },
      { name: "Boiron Bergamotte-Püree", amount: 30, unit: "ml" },
      { name: "Ronnefeldt Assam Earl Grey", amount: 50, unit: "ml" },
      { name: "Zuckersirup", amount: 20, unit: "ml" },
    ],
    method: "Muddeln, Shake, Fine Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze, Ingwer",
    ice: "Würfel",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Der Grinch"],
  },
  {
    name: "Vieux Carré",
    category: "Whisky",
    basePortions: 1,
    ingredients: [
      { name: "Sazerac Rye", amount: 35, unit: "ml" },
      { name: "Hennessy V.S.O.P.", amount: 35, unit: "ml" },
      { name: "Antica Formula", amount: 20, unit: "ml" },
      { name: "DOM Bénédictine", amount: 10, unit: "ml" },
      { name: "Angostura Bitters", amount: 2, unit: "dash" },
    ],
    method: "Stir & Strain",
    glass: "Nick & Nora",
    garnish: "Orangenzeste",
    ice: "–",
    pairsWith: ["Old Fashioned", "Manhattan", "Sazerac"],
  },
  {
    name: "Watermelon Man",
    category: "Vodka",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 40, unit: "ml" },
      { name: "Monin Melone-Sirup", amount: 30, unit: "ml" },
      { name: "Zitrone", amount: 25, unit: "ml" },
      { name: "Minzblätter (8–10)", amount: 9, unit: "stk" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (DOF)",
    garnish: "Minze",
    ice: "Crushed Eis",
    pairsWith: ["Moscow Mule", "Cosmopolitan", "Screwdriver"],
  },
  {
    name: "Asian Moskito",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Minzblätter", amount: 10, unit: "stk" },
      { name: "Limettenblätter", amount: 3, unit: "stk" },
      { name: "Boiron Kalamansi-Püree", amount: 40, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Schweppes Bitter Lemon (zum Auffüllen)", amount: 140, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Limettenblätter, Minze",
    ice: "Eiswürfel",
    pairsWith: ["Basil Cooler", "Der Grinch", "Captain Blaubär"],
  },
  {
    name: "Asian Mule",
    category: "Vodka",
    basePortions: 1,
    ingredients: [
      { name: "Ketel One Vodka", amount: 45, unit: "ml" },
      { name: "Minzblätter", amount: 10, unit: "stk" },
      { name: "Limettenblätter", amount: 3, unit: "stk" },
      { name: "Boiron Kalamansi-Püree", amount: 20, unit: "ml" },
      { name: "Zuckersirup", amount: 15, unit: "ml" },
      { name: "Schweppes Ginger Beer (zum Auffüllen)", amount: 120, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Limettenblätter, Minze",
    ice: "Würfel",
    pairsWith: ["Moscow Mule", "Cosmopolitan", "Screwdriver"],
  },
  {
    name: "Aviation",
    category: "Gin",
    basePortions: 1,
    ingredients: [
      { name: "Tanqueray London Dry Gin", amount: 45, unit: "ml" },
      { name: "Crème de Violette", amount: 10, unit: "ml" },
      { name: "Maraschino-Likör", amount: 10, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
    ],
    method: "Shake, Fine Strain",
    glass: "V-Form-Glas",
    garnish: "Zitronenzeste",
    ice: "–",
    pairsWith: ["Gimlet", "Tom Collins", "Last Word"],
  },
  {
    name: "Basil Cooler",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Basilikumblätter (5–6)", amount: 5, unit: "stk" },
      { name: "Rauch Eistee Pfirsich", amount: 30, unit: "ml" },
      { name: "Zuckersirup", amount: 10, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
      { name: "The Basil Limo (zum Auffüllen)", amount: 150, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Basilikumblatt",
    ice: "Würfel",
    pairsWith: ["Asian Moskito", "Der Grinch", "Captain Blaubär"],
  },
  {
    name: "Bee's Knees Niece",
    category: "Gin",
    basePortions: 1,
    ingredients: [
      { name: "Earl-Grey-infused Bombay Sapphire Gin", amount: 50, unit: "ml" },
      { name: "Giffard Honig-Sirup", amount: 25, unit: "ml" },
      { name: "Boiron Bergamotte-Püree", amount: 30, unit: "ml" },
      { name: "Zitrone", amount: 10, unit: "ml" },
    ],
    method: "Shake, Fine Strain",
    glass: "Coupette",
    garnish: "Zeste oder Limettenrad",
    ice: "",
    pairsWith: ["Gimlet", "Tom Collins", "Aviation"],
  },
  {
    name: "Beery Negroni Sbagliato",
    category: "Aperitivo & Spritz",
    basePortions: 1,
    ingredients: [
      { name: "Beery Campari-Vermouth-Mix", amount: 70, unit: "ml" },
      { name: "3³ Secco (Weingut Pfannebecker)", amount: 70, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Tumbler (DOF)",
    garnish: "Dry/Fresh Orange, TK Beeren",
    ice: "Würfel",
    pairsWith: ["Aperol Spritz", "Americano", "Negroni Sbagliato"],
  },
  {
    name: "Captain Blaubär",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Monin Blaubeeren-Püree", amount: 70, unit: "ml" },
      { name: "Zitronensaft", amount: 20, unit: "ml" },
      { name: "Vaihinger Bananensaft", amount: 70, unit: "ml" },
      { name: "Blue Curaçao Sirup", amount: 10, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "–",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Der Grinch"],
  },
  {
    name: "Cosmo 1934",
    category: "Gin",
    basePortions: 1,
    ingredients: [
      { name: "Bombay Sapphire Gin", amount: 50, unit: "ml" },
      { name: "Giffard Himbeersirup", amount: 25, unit: "ml" },
      { name: "Zitronensaft", amount: 30, unit: "ml" },
      { name: "Eiweiß", amount: 15, unit: "ml" },
      { name: "Martini Bianco", amount: 10, unit: "ml" },
      { name: "Cointreau", amount: 10, unit: "ml" },
    ],
    method: "Shaken und Strain",
    glass: "Coupette",
    garnish: "",
    ice: "–",
    pairsWith: ["Gimlet", "Tom Collins", "Aviation"],
  },
  {
    name: "Cream Berry",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [{ name: "Pre-Mix", amount: 100, unit: "ml" }],
    method: "Stir auf Würfel oder Block",
    glass: "Tumbler (DOF)",
    garnish: "Espuma",
    ice: "Würfel",
  },
  {
    name: "Cucumber Elderflower Collins",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Tanqueray 0,0% Gin", amount: 45, unit: "ml" },
      { name: "Giffard Holunderblütensirup", amount: 20, unit: "ml" },
      { name: "Zitrone", amount: 25, unit: "ml" },
      { name: "Gurkenscheiben (2–3, muddeln)", amount: 2, unit: "stk" },
      { name: "Schweppes Soda Water (zum Auffüllen)", amount: 120, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Zitronenscheibe oder Zeste",
    ice: "Würfel",
    pairsWith: ["Gimlet", "Tom Collins", "Aviation"],
  },
  {
    name: "Der Grinch",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Vaihinger Apfelsaft", amount: 100, unit: "ml" },
      { name: "Giffard Apfelsirup", amount: 35, unit: "ml" },
      { name: "Boiron Kiwi-Püree", amount: 40, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "–",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Captain Blaubär"],
  },
  {
    name: "Espadin Kick",
    category: "Tequila & Mezcal",
    basePortions: 1,
    ingredients: [
      { name: "San Cosme Mezcal", amount: 50, unit: "ml" },
      { name: "Limette", amount: 25, unit: "ml" },
      { name: "Agavensirup", amount: 20, unit: "ml" },
      { name: "Kardamomkapseln", amount: 3, unit: "stk" },
    ],
    method: "Shake & Fine Strain",
    glass: "Tumbler (SOF)",
    garnish: "Absinth-Spray und Limettenzeste",
    ice: "Block",
    pairsWith: ["Tequila Sunrise", "Oaxaca Old Fashioned"],
  },
  {
    name: "Frozen KIBA",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Banane", amount: 1, unit: "stk" },
      { name: "Vaihinger Bananensaft", amount: 70, unit: "ml" },
      { name: "Vaihinger Sauerkirschsaft", amount: 50, unit: "ml" },
      { name: "Sahne", amount: 30, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "–",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Der Grinch"],
  },
  {
    name: "Fruit of the Loom",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [
      { name: "Boiron Mango-Püree", amount: 35, unit: "ml" },
      { name: "Erdbeer-Püree", amount: 35, unit: "ml" },
      { name: "Zitrone", amount: 15, unit: "ml" },
      { name: "Giffard Vanille-Sirup", amount: 10, unit: "ml" },
      { name: "Vaihinger Ananassaft", amount: 70, unit: "ml" },
    ],
    method: "Alles mit Crushed Eis im großen Tin mit Stabmixer mischen",
    glass: "Kl. Softglas",
    garnish: "",
    ice: "Crushed Ice",
    pairsWith: ["Asian Moskito", "Basil Cooler", "Der Grinch"],
  },
  {
    name: "Gustavo",
    category: "Tequila & Mezcal",
    basePortions: 1,
    ingredients: [
      { name: "Jose Cuervo 100% Agave Tequila", amount: 45, unit: "ml" },
      { name: "Giffard Hibiskus-Sirup", amount: 15, unit: "ml" },
      { name: "Limette", amount: 20, unit: "ml" },
      { name: "Thomas Henry Pink Grapefruit (zum Auffüllen, 120–140 ml)", amount: 130, unit: "ml" },
    ],
    method: "Build in Glas",
    glass: "Longdrinkglas",
    garnish: "Salzrand, Dry Grapefruit",
    ice: "Würfel",
    pairsWith: ["Margarita", "Tommy's Margarita", "Paloma"],
  },
  {
    name: "Inspired by Snickers",
    category: "Alkoholfrei",
    basePortions: 1,
    ingredients: [{ name: "Pre-Mix", amount: 80, unit: "ml" }],
    method: "Stir & Strain",
    glass: "Tumbler (SOF)",
    garnish: "Gewürfelter Snickers",
    ice: "Block",
  },
];
