// Erster Entwurf des Produktkatalogs, automatisch aus den Zutaten aller
// Rezepte (Klassiker + Hausrezepte) zusammengestellt. Bekannte Spirituosen/
// Liköre/Aperitifs haben ein volles Profil (eigene Formulierungen auf Basis
// allgemein bekannten Fachwissens). Frischware, Sirupe, Mixer usw. haben
// erstmal nur Basisdaten – wird ersetzt/ergänzt, sobald die echte
// Produktliste der Bar vorliegt.
export const PRODUCTS = [
  // ---------- GIN ----------
  {
    name: "Bombay Gin", group: "Gin", subGroup: "",
    category: "London Dry Gin · England",
    abv: "40 % vol",
    tastingNotes: "Zitrus, Koriander, Angelikawurzel, mild und weich",
    story: "Bombay Sapphire wird mit zehn Botanicals per Dampfinfusion statt klassischer Mazeration aromatisiert, was ihm sein besonders sanftes Profil gibt. Die blaue Flasche macht ihn am Regal sofort erkennbar.",
    service: "Gin Tonic, Martini, florale/zitrische Cocktails",
    alternatives: "Tanqueray Gin oder ein anderer milder London Dry Gin",
    production: "Dampfinfusion der Botanicals statt Einlegen in den Alkohol",
    allergens: "Keine bekannten",
  },
  {
    name: "Bene Dry Gin", group: "Gin", subGroup: "",
    category: "Dry Gin · Deutschland",
    abv: "42 % vol (bitte gegen Flasche prüfen)",
    tastingNotes: "Klassisch wacholderbetont mit zitrischer Frische",
    story: "Ein handwerklich hergestellter deutscher Dry Gin, der als solide Basis für klassische Gin-Cocktails wie den Martinez dient.",
    service: "Gerührte Cocktails (Martinez, Martini), Gin Tonic",
    alternatives: "Bombay Gin, Tanqueray Gin",
    production: "Kleinbrennerei-Destillat",
    allergens: "Keine bekannten",
  },
  {
    name: "Tanqueray Gin", group: "Gin", subGroup: "",
    category: "London Dry Gin · Schottland",
    abv: "43,1 % vol",
    tastingNotes: "Kräftig wacholderbetont, pfeffrig-würzig, trocken",
    story: "Tanqueray wird seit 1830 nach demselben Grundrezept mit nur vier Botanicals gebrannt und ist einer der meistverkauften London Dry Gins weltweit.",
    service: "Martini, Gin Tonic, Negroni",
    alternatives: "Beefeater oder ein anderer klassischer London Dry Gin",
    production: "Vierfach destilliert, nur vier Botanicals (u. a. Wacholder, Koriander, Angelikawurzel, Süßholz)",
    allergens: "Keine bekannten",
  },
  {
    name: "Tanqueray Sevilla", group: "Gin", subGroup: "",
    category: "Gin mit Orangenaroma · Schottland",
    abv: "41,3 % vol",
    tastingNotes: "Bitterorange, süßlich-fruchtig, dezent würzig",
    story: "Mit sevillanischen Bitterorangen aromatisierte Tanqueray-Variante, entwickelt für fruchtig-bittere Cocktail-Kreationen.",
    service: "Gimlet-Variationen, Highballs mit Zitrus/Thymian",
    alternatives: "Klassischer Tanqueray Gin plus etwas Orangenlikör",
    production: "Basis-Gin mit zusätzlicher Bitterorangen-Aromatisierung",
    allergens: "Keine bekannten",
  },
  {
    name: "Tanqueray 0,0% Gin", group: "Gin", subGroup: "",
    category: "Alkoholfreier Gin-Ersatz · Schottland",
    abv: "0,0 % vol",
    tastingNotes: "Wacholder- und Zitrusnoten ohne Alkoholschärfe",
    story: "Alkoholfreie Variante des Tanqueray-Rezepts für Gäste, die auf Alkohol verzichten möchten, ohne auf den Geschmack zu verzichten.",
    service: "Alkoholfreie Cocktails, Mocktail-Gin-Tonic",
    alternatives: "Andere alkoholfreie Gin-Alternativen",
    production: "Botanicals-Extrakt ohne Alkoholgärung",
    allergens: "Keine bekannten",
  },

  // ---------- VODKA ----------
  {
    name: "Ketel One Vodka", group: "Vodka", subGroup: "",
    category: "Wheat Vodka · Niederlande",
    abv: "40 % vol",
    tastingNotes: "Sehr weich, leicht süßlich, dezente Getreidenote",
    story: "Ketel One wird seit 1691 von der Familie Nolet in Schiedam hergestellt, benannt nach dem alten Kupferdestillationskessel 'Distilleerketel #1'.",
    service: "Pur eisgekühlt, Martini, Melonen-/Beeren-Cocktails",
    alternatives: "Grey Goose, Belvedere oder ein anderer Premium-Weizenvodka",
    production: "Kupferbrand-Destillation in traditionellen Pot Stills",
    allergens: "Aus Weizen – destillierter Alkohol gilt meist als glutenfrei",
  },

  // ---------- RUM / CACHAÇA ----------
  {
    name: "Havana Club 3", group: "Rum & Cachaça", subGroup: "Weißer Rum",
    category: "White Rum · Kuba",
    abv: "40 % vol",
    tastingNotes: "Leicht, trocken, dezent süß mit Zuckerrohrfrische",
    story: "Havana Club ist die bekannteste kubanische Rum-Marke; die '3 Años'-Variante ist der helle Standard-Rum für klassische kubanische Drinks wie Mojito und Cuba Libre.",
    service: "Mojito, Cuba Libre, Daiquiri",
    alternatives: "Jeder andere weiße Rum",
    production: "Mindestens 3 Jahre Fassreifung, danach filtriert",
    allergens: "Keine bekannten",
  },
  {
    name: "Gosling's Rum", group: "Rum & Cachaça", subGroup: "Dunkler Rum",
    category: "Dark Rum (Black Seal) · Bermuda",
    abv: "40 % vol",
    tastingNotes: "Karamell, Melasse, Gewürze, kräftig-rund",
    story: "Untrennbar mit dem Dark 'n' Stormy verbunden – die Bermuda-Destillerie hat sich den Namen dieses Cocktails sogar markenrechtlich schützen lassen.",
    service: "Dark 'n' Stormy, pur oder auf Eis",
    alternatives: "Anderer dunkler Rum",
    production: "Blend aus verschiedenen gereiften Rums",
    allergens: "Keine bekannten",
  },
  {
    name: "Matusalem Rum 15yo", group: "Rum & Cachaça", subGroup: "Gereifter Rum (Sipping)",
    category: "Aged Rum (Solera) · Dominikanische Republik",
    abv: "40 % vol",
    tastingNotes: "Komplex, Trockenfrüchte, Karamell, Eiche, weich",
    story: "Wird im Solera-Verfahren gereift, bei dem jüngerer Rum kontinuierlich mit älteren Jahrgängen vermischt wird – die '15 Años' bezieht sich auf den ältesten enthaltenen Rum im Blend.",
    service: "Pur/on the rocks als Digestif, anspruchsvolle Rum-Cocktails",
    alternatives: "Anderer gereifter Sipping-Rum",
    production: "Solera-Reifesystem wie beim Sherry",
    allergens: "Keine bekannten",
  },
  {
    name: "Smith & Cross Rum", group: "Rum & Cachaça", subGroup: "Overproof Rum",
    category: "Jamaica Pot Still Rum · Jamaika",
    abv: "57 % vol",
    tastingNotes: "Sehr intensiv, funky, Banane, Gewürze, hoher Esteranteil",
    story: "Traditioneller Jamaika-Rum aus Pot-Still-Destillation mit hohem Esteranteil, geschätzt von Tiki-Bartendern für seinen unverwechselbar 'funky' Charakter.",
    service: "Tiki-Cocktails, Mai-Tai-Variationen, meist als Blend-Partner",
    alternatives: "Ein anderer hocharomatischer Jamaika-Rum",
    production: "Pot-Still-Destillation, hoher natürlicher Estergehalt",
    allergens: "Keine bekannten",
  },

  // ---------- WHISKY / WHISKEY ----------
  {
    name: "Bulleit Bourbon", group: "Whisky", subGroup: "Bourbon",
    category: "High-Rye Bourbon · USA",
    abv: "45 % vol",
    tastingNotes: "Würzig-pfeffrig für einen Bourbon, Vanille, Eiche",
    story: "Verwendet einen ungewöhnlich hohen Roggenanteil in der Maische, wodurch er würziger und trockener schmeckt als klassische Bourbons.",
    service: "Old Fashioned, Suffering Bastard, pur",
    alternatives: "Anderer Bourbon mit hohem Roggenanteil",
    production: "High-Rye-Mash-Bill (hoher Roggenanteil im Bourbon)",
    allergens: "Aus Getreide – destillierter Alkohol gilt meist als glutenfrei",
  },
  {
    name: "Sazerac Rye", group: "Whisky", subGroup: "Rye",
    category: "Rye Whiskey · USA",
    abv: "45 % vol",
    tastingNotes: "Würzig, kräftig, Anisspuren, trocken",
    story: "Nach dem gleichnamigen New-Orleans-Cocktail benannter Rye Whiskey der Buffalo-Trace-Destillerie, speziell für Sazerac und Vieux Carré konzipiert.",
    service: "Sazerac, Vieux Carré, Manhattan",
    alternatives: "Anderer kräftiger Rye Whiskey",
    production: "Klassische Rye-Whiskey-Destillation und Fassreifung",
    allergens: "Aus Getreide (Roggen) – destillierter Alkohol gilt meist als glutenfrei",
  },

  // ---------- TEQUILA / MEZCAL ----------
  {
    name: "Jose Cuervo Tequila", group: "Tequila & Mezcal", subGroup: "Tequila",
    category: "Tequila · Mexiko",
    abv: "38 % vol",
    tastingNotes: "Mild-agavig, leicht süßlich, unkompliziert",
    story: "Älteste und meistverkaufte Tequila-Marke der Welt, seit 1795 in Familienbesitz – der zugängliche Standard-Tequila für Longdrinks.",
    service: "Paloma-Variationen, Tequila-Highballs",
    alternatives: "Anderer milder Mischtequila",
    production: "Klassische Tequila-Destillation, teils mit Zuckerrohr-Zusatz",
    allergens: "Keine bekannten",
  },
  {
    name: "San Cosme Mezcal", group: "Tequila & Mezcal", subGroup: "Mezcal",
    category: "Mezcal Espadín · Mexiko",
    abv: "40–46 % vol",
    tastingNotes: "Rauchig, agavig, leicht mineralisch",
    story: "Traditionell in Oaxaca hergestellter Espadín-Mezcal – bringt den charakteristischen Rauchcharakter in moderne Cocktails wie den Espadin Kick.",
    service: "Espadin Kick, andere rauchig-agavige Cocktails",
    alternatives: "Anderer Espadín-Mezcal",
    production: "Espadín-Agave, traditionelle Erdgruben-Röstung",
    allergens: "Keine bekannten",
  },

  // ---------- BRANDY / COGNAC ----------
  {
    name: "Hennessy VSOP", group: "Brände", subGroup: "Cognac",
    category: "Cognac VSOP · Frankreich",
    abv: "40 % vol",
    tastingNotes: "Vanille, getrocknete Früchte, dezente Würze, weich",
    story: "Eines der weltweit größten Cognac-Häuser; 'VSOP' garantiert eine Mindestreifung von vier Jahren für den jüngsten enthaltenen Brand.",
    service: "Vieux Carré, pur als Digestif",
    alternatives: "Anderer VSOP-Cognac",
    production: "Mindestens 4 Jahre Fassreifung (VSOP-Klassifikation)",
    allergens: "Keine bekannten",
  },

  // ---------- LIKÖRE / APERITIFS ----------
  {
    name: "Amaretto", group: "Liköre & Aperitifs", subGroup: "Steinfrucht-/Mandellikör",
    category: "Mandellikör · Italien",
    abv: "21–28 % vol",
    tastingNotes: "Süß, Marzipan/Mandel, warm-würzig",
    story: "Wird meist aus Aprikosenkernen statt echten Mandeln aromatisiert, was seinen typischen Marzipan-Ton erzeugt. Bekannteste Marke: Disaronno.",
    service: "Amaretto Sour, Godfather, French Connection",
    alternatives: "Anderer Mandellikör",
    production: "Aromatisierung meist über Aprikosenkern-Destillat",
    allergens: "Kann Spuren von Nüssen/Aprikosenkernen enthalten – bei Nussallergie prüfen",
  },
  {
    name: "Aperol", group: "Liköre & Aperitifs", subGroup: "Bitter-Aperitif",
    category: "Bitter-Aperitif · Italien",
    abv: "11 % vol",
    tastingNotes: "Bitterorange, Rhabarber, süß-herb, leicht",
    story: "1919 in Padua entwickelt und durch den Aperol Spritz seit den 2000er-Jahren zum meistverkauften Aperitif-Likör der Welt geworden.",
    service: "Aperol Spritz, leichte Longdrinks",
    alternatives: "Campari (herber/stärker)",
    production: "Mazeration von Bitterorange, Rhabarber und Kräutern",
    allergens: "Keine bekannten",
  },
  {
    name: "Campari", group: "Liköre & Aperitifs", subGroup: "Bitter-Aperitif",
    category: "Bitterlikör · Italien",
    abv: "25 % vol",
    tastingNotes: "Kräftig bitter, Bitterorange, Kräuter, intensiv rot",
    story: "1860 von Gaspare Campari in Novara entwickelt; die genaue Kräutermischung ist bis heute geheim. Basiszutat von Negroni und Americano.",
    service: "Negroni, Americano, Garibaldi",
    alternatives: "Aperol (milder/süßer)",
    production: "Mazeration von Kräutern, Wurzeln und Bitterorangenschalen",
    allergens: "Keine bekannten",
  },
  {
    name: "Cointreau", group: "Liköre & Aperitifs", subGroup: "Orangenlikör",
    category: "Orangenlikör (Triple Sec) · Frankreich",
    abv: "40 % vol",
    tastingNotes: "Klar-orangig, süß-herb, kräftig aromatisch",
    story: "Seit 1875 aus süßen und bitteren Orangenschalen destilliert – Premium-Referenz unter den Orangenlikören, Standardzutat in Margarita, Cosmopolitan und Sidecar.",
    service: "Margarita, Cosmopolitan, Sidecar, White Lady",
    alternatives: "Anderer Triple Sec (Grand Marnier für kräftigere Note)",
    production: "Destillation von süßen und bitteren Orangenschalen",
    allergens: "Keine bekannten",
  },
  {
    name: "Grand Marnier", group: "Liköre & Aperitifs", subGroup: "Orangenlikör",
    category: "Orangenlikör auf Cognac-Basis · Frankreich",
    abv: "40 % vol",
    tastingNotes: "Orange, Vanille, Cognac-Tiefe, kräftig",
    story: "Kombiniert Bitterorangen-Destillat mit Cognac statt neutralem Alkohol, was ihm mehr Tiefe als klassischem Triple Sec gibt.",
    service: "Mai-Tai-Variationen, als Floater, Digestif",
    alternatives: "Cointreau (leichter, weniger Cognac-Tiefe)",
    production: "Bitterorangen-Destillat auf Cognac-Basis",
    allergens: "Keine bekannten",
  },
  {
    name: "Maraschino-Likör", group: "Liköre & Aperitifs", subGroup: "Steinfrucht-/Mandellikör",
    category: "Kirschlikör · Italien/Kroatien",
    abv: "32 % vol",
    tastingNotes: "Trocken-bittermandelig, Steinobstkern, nicht fruchtig-süß",
    story: "Wird aus Marasca-Sauerkirschen samt Kernen destilliert, was ihm seinen trockenen, mandeligen Charakter gibt – Schlüsselzutat in Aviation und Last Word.",
    service: "Aviation, Last Word, Hemingway Daiquiri",
    alternatives: "Kein direkter Ersatz – Charakter ist einzigartig",
    production: "Destillation aus Marasca-Kirschen inklusive Kernen",
    allergens: "Keine bekannten",
  },
  {
    name: "Kaffeelikör", group: "Liköre & Aperitifs", subGroup: "Kaffeelikör",
    category: "Kaffeelikör · diverse Herkunft",
    abv: "20–26 % vol",
    tastingNotes: "Kaffee, Röstaromen, süß",
    story: "Verbindet Kaffeeextrakt mit Zuckerrohr-/Neutralalkohol (bekannteste Marke: Kahlúa) – unverzichtbar in Espresso Martini und White Russian.",
    service: "Espresso Martini, White Russian, Mudslide",
    alternatives: "Anderer Kaffeelikör",
    production: "Mazeration/Extraktion von Kaffee, gesüßt",
    allergens: "Enthält Koffein",
  },
  {
    name: "Kakaolikör (Crème de Cacao)", group: "Liköre & Aperitifs", subGroup: "Cremelikör",
    category: "Kakaolikör · diverse Herkunft",
    abv: "20–24 % vol",
    tastingNotes: "Schokoladig-süß; weiße Variante ohne Farbe, gleiche Kakaonote",
    story: "Aus gerösteten Kakaobohnen aromatisiert, gibt Cocktails wie Grasshopper oder Brandy Alexander ihre dessertartige Schokoladennote.",
    service: "Grasshopper, Brandy Alexander, Chocolate Martini",
    alternatives: "Braune und weiße Variante meist untereinander austauschbar",
    production: "Aromatisierung mit geröstetem Kakao",
    allergens: "Keine bekannten",
  },
  {
    name: "Grüner Crème de Menthe", group: "Liköre & Aperitifs", subGroup: "Cremelikör",
    category: "Pfefferminzlikör · diverse Herkunft",
    abv: "20–24 % vol",
    tastingNotes: "Intensiv Pfefferminze, süß, kühlend",
    story: "Die grüne Färbung ist rein optisch – geschmacklich identisch mit der weißen Variante. Namensgebend für den grünen Grasshopper.",
    service: "Grasshopper",
    alternatives: "Weißer Crème de Menthe (nur Farbe unterscheidet sich)",
    production: "Aromatisierung mit Pfefferminzöl",
    allergens: "Keine bekannten",
  },
  {
    name: "Weißer Crème de Menthe", group: "Liköre & Aperitifs", subGroup: "Cremelikör",
    category: "Pfefferminzlikör · diverse Herkunft",
    abv: "20–24 % vol",
    tastingNotes: "Intensiv Pfefferminze, süß, kühlend, farblos",
    story: "Geschmacklich identisch mit der grünen Variante, meist für Cocktails verwendet, bei denen keine grüne Farbe erwünscht ist (z. B. Stinger).",
    service: "Stinger",
    alternatives: "Grüner Crème de Menthe (nur Farbe unterscheidet sich)",
    production: "Aromatisierung mit Pfefferminzöl",
    allergens: "Keine bekannten",
  },
  {
    name: "Crème de Violette", group: "Liköre & Aperitifs", subGroup: "Kräuter-/Blütenlikör",
    category: "Veilchenlikör · Frankreich",
    abv: "20 % vol",
    tastingNotes: "Floral, veilchenartig, leicht süß",
    story: "Verschwand jahrzehntelang fast völlig vom Markt und machte den klassischen Aviation-Cocktail lange schwer authentisch mixbar – seit den 2000er-Jahren wieder verfügbar.",
    service: "Aviation (charakteristische Lavendel-Farbe)",
    alternatives: "Kein wirklicher Ersatz für den floralen Ton",
    production: "Aromatisierung/Mazeration mit Veilchenblüten",
    allergens: "Keine bekannten",
  },
  {
    name: "Orange Curaçao", group: "Liköre & Aperitifs", subGroup: "Orangenlikör",
    category: "Orangenlikör · diverse Herkunft",
    abv: "30–40 % vol",
    tastingNotes: "Orangig, etwas kräftiger/dunkler als Triple Sec",
    story: "Benannt nach der karibischen Insel Curaçao, deren bittere Laraha-Orangenschalen ursprünglich für den charakteristischen Geschmack sorgten – klassisch im Mai Tai.",
    service: "Mai Tai, Tiki-Cocktails",
    alternatives: "Cointreau/Triple Sec (heller, weniger süß)",
    production: "Destillation/Mazeration von (Bitter-)Orangenschalen",
    allergens: "Keine bekannten",
  },
  {
    name: "Bénédictine", group: "Liköre & Aperitifs", subGroup: "Kräuter-/Blütenlikör",
    category: "Kräuterlikör (DOM) · Frankreich",
    abv: "40 % vol",
    tastingNotes: "Honigsüß, Kräuter, Gewürze, warm-komplex",
    story: "Seit dem 16. Jahrhundert nach einem angeblichen Mönchsrezept aus über 27 Kräutern und Gewürzen hergestellt – 'DOM' auf dem Etikett steht für 'Deo Optimo Maximo'.",
    service: "Vieux Carré, Bee's Knees Niece",
    alternatives: "Kein direkter Ersatz, ggf. anderer Kräuterlikör",
    production: "Mazeration von über 27 Kräutern und Gewürzen, Fassreifung",
    allergens: "Keine bekannten",
  },
  {
    name: "Grüner Chartreuse", group: "Liköre & Aperitifs", subGroup: "Kräuter-/Blütenlikör",
    category: "Kräuterlikör · Frankreich",
    abv: "55 % vol",
    tastingNotes: "Sehr intensiv kräuterig-würzig, leicht süß, hochprozentig",
    story: "Wird von Kartäuser-Mönchen nach einem streng geheimen Rezept aus 130 Kräutern hergestellt – nur zwei Mönche kennen gleichzeitig die vollständige Rezeptur.",
    service: "Last Word",
    alternatives: "Kein direkter Ersatz – einzigartiges Profil",
    production: "Mazeration von rund 130 Kräutern und Pflanzen nach Klosterrezept",
    allergens: "Keine bekannten",
  },
  {
    name: "Cherry Heering (Kirschlikör)", group: "Liköre & Aperitifs", subGroup: "Fruchtlikör",
    category: "Kirschlikör · Dänemark",
    abv: "24 % vol",
    tastingNotes: "Dunkle Kirsche, süß-herb, weinig-tief",
    story: "Wird seit 1818 in Dänemark hergestellt und ist die klassische Kirschlikör-Zutat im Singapore Sling.",
    service: "Singapore Sling",
    alternatives: "Anderer dunkler Kirschlikör",
    production: "Mazeration dunkler Kirschen, Fassreifung",
    allergens: "Keine bekannten",
  },
  {
    name: "Helbing Kümmel", group: "Liköre & Aperitifs", subGroup: "Kräuter-/Blütenlikör",
    category: "Kümmelbrand · Deutschland",
    abv: "38–40 % vol",
    tastingNotes: "Kräftig kümmelig-würzig, kräuterbitter",
    story: "Traditioneller norddeutscher Kräuterschnaps auf Kümmelbasis – eine regionale Spezialität, die dem hauseigenen Sea Breeze seine markante Würze gibt.",
    service: "Hauseigener Sea Breeze, pur als Digestif",
    alternatives: "Anderer Kümmelschnaps",
    production: "Destillation/Aromatisierung mit Kümmel und Kräutern",
    allergens: "Keine bekannten",
  },

  // ---------- WERMUT / APERITIF-WEIN ----------
  {
    name: "Antica Formula", group: "Wermut & Aperitif-Wein", subGroup: "",
    category: "Premium roter Wermut (Carpano) · Italien",
    abv: "16,5 % vol",
    tastingNotes: "Intensiv würzig-süß, Vanille, Zimt, sehr komplex",
    story: "Rekonstruktion des allerersten Wermut-Rezepts von 1786 – gilt als Premium-Standard, bevorzugt für hochwertige Manhattans und den Martinez.",
    service: "Martinez, Manhattan, Boulevardier",
    alternatives: "Anderer hochwertiger roter Wermut",
    production: "Traditionsrezeptur mit Vanille, Zimt und weiteren Gewürzen",
    allergens: "Enthält Sulfite (weinbasiert)",
  },
  {
    name: "Martini Florale", group: "Wermut & Aperitif-Wein", subGroup: "",
    category: "Aromatisierter Wermut (floral) · Italien",
    abv: "14,4 % vol",
    tastingNotes: "Blumig, leicht süß, Holunder-/Blütennoten",
    story: "Florale Wermut-Variante von Martini & Rossi mit Blütenaromen, geeignet für leichte, aromatische Cocktails wie den hauseigenen Morgentau.",
    service: "Hauseigener Morgentau, leichte Sommer-Cocktails",
    alternatives: "Anderer floraler/aromatisierter Wermut",
    production: "Wermutbasis mit Blütenaromatisierung",
    allergens: "Enthält Sulfite (weinbasiert)",
  },
  {
    name: "Ramazzotti Rosato", group: "Wermut & Aperitif-Wein", subGroup: "",
    category: "Roséwein-Aperitif · Italien",
    abv: "15 % vol",
    tastingNotes: "Fruchtig-frisch, leichte Kräuterbittere, roséweinartig",
    story: "Roséfarbene Aperitif-Weiterentwicklung der italienischen Amaro-Marke Ramazzotti, konzipiert für leichte, spritzige Sommerdrinks.",
    service: "Hauseigener Rhubarb Rosato, Spritz-Varianten",
    alternatives: "Anderer Rosé-Aperitif oder Aperol in geringerer Menge",
    production: "Roséwein-Basis mit Kräuterauszügen",
    allergens: "Enthält Sulfite (weinbasiert)",
  },

  // ---------- BITTERS ----------
  {
    name: "Angostura Bitters", group: "Bitters", subGroup: "",
    category: "Aromatische Bitters · Trinidad",
    abv: "44,7 % vol",
    tastingNotes: "Intensiv würzig-bitter, Gewürznelke, Zimt, Enzian",
    story: "1824 ursprünglich als Medizin gegen Magenbeschwerden entwickelt und heute die meistverwendeten Bitters der Barwelt – die Rezeptur ist bis heute geheim.",
    service: "Nur tropfenweise (Dash) dosieren, nicht pur trinken",
    alternatives: "Kein direkter Ersatz für den charakteristischen Geschmack",
    production: "Mazeration von Gewürzen und Kräutern (u. a. Enzianwurzel), Rezeptur geheim",
    allergens: "Keine bekannten",
  },
  {
    name: "Peychaud's Bitters", group: "Bitters", subGroup: "",
    category: "Aromatische Bitters · USA (New Orleans)",
    abv: "35 % vol",
    tastingNotes: "Anis-/Nelkenbetont, süßer und blumiger als Angostura",
    story: "Von Antoine Amédée Peychaud im frühen 19. Jahrhundert in New Orleans entwickelt, untrennbar mit dem Sazerac verbunden.",
    service: "Nur tropfenweise (Dash) dosieren",
    alternatives: "Angostura Bitters (anderes Profil, aber nutzbar)",
    production: "Mazeration von Gewürzen, Rezeptur firmengeheim",
    allergens: "Keine bekannten",
  },

  // ---------- SCHAUMWEIN ----------
  {
    name: "A-Rosa Sekt", group: "Schaumwein", subGroup: "",
    category: "Sekt · Deutschland",
    abv: "11,5 % vol",
    tastingNotes: "Frisch-fruchtig, unkompliziert",
    story: "Hauseigener Sekt für die Beery-Negroni-Sbagliato-Variante und andere Spritz-Cocktails.",
    service: "Hauseigener Negroni Sbagliato",
    alternatives: "Anderer trockener Sekt/Prosecco",
    production: "",
    allergens: "Enthält Sulfite",
  },

  // ---------- SIRUPE ----------
  { name: "Zuckersirup", group: "Sirup", subGroup: "", category: "Sirup (Basis) · Eigenherstellung", abv: "", tastingNotes: "Neutral süß", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Honig-Sirup", group: "Sirup", subGroup: "", category: "Sirup · Eigenherstellung", abv: "", tastingNotes: "Honigsüß, rund", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Himbeersirup", group: "Sirup", subGroup: "", category: "Fruchtsirup", abv: "", tastingNotes: "Süß-fruchtig, Himbeere", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Grenadine", group: "Sirup", subGroup: "", category: "Fruchtsirup (Granatapfel)", abv: "", tastingNotes: "Süß-herb, Granatapfel, tiefrot", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Orgeat-Sirup (Mandelsirup)", group: "Sirup", subGroup: "", category: "Sirup (Mandel)", abv: "", tastingNotes: "Mandelig-süß, Orangenblütennote", story: "", service: "", alternatives: "", production: "", allergens: "Enthält Mandeln (Nussallergie beachten)" },
  { name: "Holunderblütensirup", group: "Sirup", subGroup: "", category: "Fruchtsirup", abv: "", tastingNotes: "Blumig-süß, Holunderblüte", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Vanille-Sirup", group: "Sirup", subGroup: "", category: "Sirup", abv: "", tastingNotes: "Süß, vanillig-warm", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Hibiskus-Sirup", group: "Sirup", subGroup: "", category: "Fruchtsirup", abv: "", tastingNotes: "Süß-säuerlich, blumig-rot", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Passionsfrucht-Sirup", group: "Sirup", subGroup: "", category: "Fruchtsirup", abv: "", tastingNotes: "Süß-säuerlich, exotisch-fruchtig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Zimt-Sirup", group: "Sirup", subGroup: "", category: "Sirup", abv: "", tastingNotes: "Warm-würzig, süß", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Agavendicksaft", group: "Sirup", subGroup: "", category: "Süßungsmittel", abv: "", tastingNotes: "Neutral-süß, dünnflüssig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Agavensirup", group: "Sirup", subGroup: "", category: "Süßungsmittel", abv: "", tastingNotes: "Neutral-süß, dünnflüssig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Monin Melone-Sirup", group: "Sirup", subGroup: "", category: "Fruchtsirup (Markenprodukt)", abv: "", tastingNotes: "Süß, Honigmelone", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Honig-Ingwer-Sirup", group: "Sirup", subGroup: "", category: "Sirup · Eigenherstellung", abv: "", tastingNotes: "Süß-scharf, Honig und Ingwer", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Limettensaft-Sirup", group: "Sirup", subGroup: "", category: "Sirup (Cordial)", abv: "", tastingNotes: "Süß-säuerlich, haltbar gemachte Limette", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Apfelsirup", group: "Sirup", subGroup: "", category: "Fruchtsirup", abv: "", tastingNotes: "Süß, Apfel", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Blue Curaçao Sirup", group: "Sirup", subGroup: "", category: "Sirup (alkoholfrei)", abv: "", tastingNotes: "Süß-orangig, kräftig blau", story: "", service: "", alternatives: "", production: "", allergens: "" },

  // ---------- PÜREES ----------
  { name: "Blaubeerenpüree", group: "Fruchtpüree", subGroup: "", category: "Fruchtpüree", abv: "", tastingNotes: "Süß-säuerlich, Blaubeere", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Erdbeer-Püree", group: "Fruchtpüree", subGroup: "", category: "Fruchtpüree", abv: "", tastingNotes: "Süß-fruchtig, Erdbeere", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Mango-Püree", group: "Fruchtpüree", subGroup: "", category: "Fruchtpüree", abv: "", tastingNotes: "Süß-tropisch, Mango", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Kiwi-Püree", group: "Fruchtpüree", subGroup: "", category: "Fruchtpüree", abv: "", tastingNotes: "Süß-säuerlich, Kiwi", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Kalamansi-Püree", group: "Fruchtpüree", subGroup: "", category: "Fruchtpüree (Zitrusfrucht)", abv: "", tastingNotes: "Säuerlich-aromatisch, zwischen Limette und Mandarine", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Weißer Pfirsichpüree", group: "Fruchtpüree", subGroup: "", category: "Fruchtpüree", abv: "", tastingNotes: "Süß, weißer Pfirsich", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Boiron Bergamotte-Püree", group: "Fruchtpüree", subGroup: "", category: "Fruchtpüree (Markenprodukt)", abv: "", tastingNotes: "Zitrisch-blumig, herb-aromatisch", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Ananas-Oleo-Saccharum", group: "Fruchtpüree", subGroup: "", category: "Zucker-Öl-Extrakt · Eigenherstellung", abv: "", tastingNotes: "Süß-fruchtig mit Zitrusschalen-Öl-Aroma", story: "", service: "", alternatives: "", production: "", allergens: "" },

  // ---------- SÄFTE ----------
  { name: "Zitronensaft", group: "Saft", subGroup: "", category: "Saft (frisch)", abv: "", tastingNotes: "Sauer, frisch", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Limettensaft", group: "Saft", subGroup: "", category: "Saft (frisch)", abv: "", tastingNotes: "Sauer, frisch, herb", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Orangensaft", group: "Saft", subGroup: "", category: "Saft (frisch)", abv: "", tastingNotes: "Süß-säuerlich, fruchtig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Grapefruitsaft", group: "Saft", subGroup: "", category: "Saft (frisch)", abv: "", tastingNotes: "Säuerlich-bitter, fruchtig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Ananassaft", group: "Saft", subGroup: "", category: "Saft", abv: "", tastingNotes: "Süß-säuerlich, tropisch", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Cranberrysaft", group: "Saft", subGroup: "", category: "Saft", abv: "", tastingNotes: "Säuerlich-herb, fruchtig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Apfelsaft", group: "Saft", subGroup: "", category: "Saft", abv: "", tastingNotes: "Süß-fruchtig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Tomatensaft", group: "Saft", subGroup: "", category: "Saft/Gemüsesaft", abv: "", tastingNotes: "Herzhaft-salzig, fruchtig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Bananensaft", group: "Saft", subGroup: "", category: "Saft", abv: "", tastingNotes: "Süß, cremig-fruchtig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Kirschsaft", group: "Saft", subGroup: "", category: "Saft", abv: "", tastingNotes: "Süß-säuerlich, Kirsche", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Yuzu", group: "Saft", subGroup: "", category: "Saft/Frischware (Zitrusfrucht)", abv: "", tastingNotes: "Aromatisch-sauer, zwischen Mandarine und Grapefruit", story: "", service: "", alternatives: "", production: "", allergens: "" },

  // ---------- FRISCHWARE / KRÄUTER ----------
  { name: "Zitrone", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Zitrusfrucht)", abv: "", tastingNotes: "Sauer, aromatisch", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Limette", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Zitrusfrucht)", abv: "", tastingNotes: "Sauer, herb-aromatisch", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Orange", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Zitrusfrucht)", abv: "", tastingNotes: "Süß-säuerlich", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Minzblätter", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Kräuter)", abv: "", tastingNotes: "Frisch-kühlend, aromatisch", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Basilikumblätter", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Kräuter)", abv: "", tastingNotes: "Würzig-frisch, leicht pfeffrig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Limettenblätter", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Kräuter, Kaffirlimette)", abv: "", tastingNotes: "Intensiv zitrisch-aromatisch", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Thymian", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Kräuter)", abv: "", tastingNotes: "Würzig-erdig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Gurkenscheiben", group: "Frischware & Kräuter", subGroup: "", category: "Frischware", abv: "", tastingNotes: "Frisch, mild-grün", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Banane", group: "Frischware & Kräuter", subGroup: "", category: "Frischware (Obst)", abv: "", tastingNotes: "Süß, cremig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Kardamomkapseln", group: "Frischware & Kräuter", subGroup: "", category: "Gewürz", abv: "", tastingNotes: "Warm-würzig, zitrisch-scharf", story: "", service: "", alternatives: "", production: "", allergens: "" },

  // ---------- MIXER / SOFTDRINKS ----------
  { name: "Ginger Beer", group: "Mixer & Softdrink", subGroup: "", category: "Mixer (Ingwerlimonade)", abv: "", tastingNotes: "Scharf-süß, intensiv Ingwer", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Sodawasser", group: "Mixer & Softdrink", subGroup: "", category: "Mixer", abv: "", tastingNotes: "Neutral, spritzig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Cola", group: "Mixer & Softdrink", subGroup: "", category: "Mixer", abv: "", tastingNotes: "Süß, karamellig-würzig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Schweppes Dry Tonic", group: "Mixer & Softdrink", subGroup: "", category: "Mixer (Tonic Water, Markenprodukt)", abv: "", tastingNotes: "Herb-bitter, Chinin", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Bitter Lemon", group: "Mixer & Softdrink", subGroup: "", category: "Mixer", abv: "", tastingNotes: "Bitter-süß, zitronig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Grapefruit-Limonade", group: "Mixer & Softdrink", subGroup: "", category: "Mixer", abv: "", tastingNotes: "Süß-säuerlich, Grapefruit", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Thomas Henry Pink Grapefruit", group: "Mixer & Softdrink", subGroup: "", category: "Mixer (Markenprodukt)", abv: "", tastingNotes: "Herb-fruchtig, rosa Grapefruit", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Fritz Rhabarber Schorle", group: "Mixer & Softdrink", subGroup: "", category: "Mixer (Markenprodukt)", abv: "", tastingNotes: "Süß-säuerlich, Rhabarber", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "The Basil Limo", group: "Mixer & Softdrink", subGroup: "", category: "Mixer (Markenprodukt)", abv: "", tastingNotes: "Erfrischend, Zitrus mit Basilikum", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Mystic Mango", group: "Mixer & Softdrink", subGroup: "", category: "Mixer (Markenprodukt)", abv: "", tastingNotes: "Süß-tropisch, Mango", story: "", service: "", alternatives: "", production: "", allergens: "" },

  // ---------- TEE / KAFFEE ----------
  { name: "Earl Grey Tee", group: "Tee & Kaffee", subGroup: "", category: "Tee", abv: "", tastingNotes: "Aromatisch, Bergamotte", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Morgentau Tee", group: "Tee & Kaffee", subGroup: "", category: "Tee (Hausmischung)", abv: "", tastingNotes: "Aromatisch, je nach Mischung", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Pfirsich Eistee", group: "Tee & Kaffee", subGroup: "", category: "Getränk (Eistee)", abv: "", tastingNotes: "Süß, Pfirsich", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Frisch gebrühter Espresso", group: "Tee & Kaffee", subGroup: "", category: "Kaffee", abv: "", tastingNotes: "Röstig-bitter, intensiv", story: "", service: "", alternatives: "", production: "", allergens: "Enthält Koffein" },
  { name: "Heißer Kaffee", group: "Tee & Kaffee", subGroup: "", category: "Kaffee", abv: "", tastingNotes: "Röstig, bitter-aromatisch", story: "", service: "", alternatives: "", production: "", allergens: "Enthält Koffein" },

  // ---------- SONSTIGES ----------
  { name: "Eiweiß", group: "Sonstiges", subGroup: "", category: "Frischware (Ei)", abv: "", tastingNotes: "Neutral, für Schaum/Textur", story: "", service: "", alternatives: "Aquafaba (veganer Ersatz)", production: "", allergens: "Enthält Ei" },
  { name: "Sahne", group: "Sonstiges", subGroup: "", category: "Milchprodukt", abv: "", tastingNotes: "Cremig, mild-süß", story: "", service: "", alternatives: "Milch (weniger cremig)", production: "", allergens: "Enthält Milch/Laktose" },
  { name: "Schlagsahne", group: "Sonstiges", subGroup: "", category: "Milchprodukt", abv: "", tastingNotes: "Cremig, mild-süß, aufgeschlagen", story: "", service: "", alternatives: "Sahne", production: "", allergens: "Enthält Milch/Laktose" },
  { name: "Milch", group: "Sonstiges", subGroup: "", category: "Milchprodukt", abv: "", tastingNotes: "Mild, cremig", story: "", service: "", alternatives: "Pflanzendrink", production: "", allergens: "Enthält Milch/Laktose" },
  { name: "Kokoscreme (Coco Lopez)", group: "Sonstiges", subGroup: "", category: "Milchersatz (Kokos, Markenprodukt)", abv: "", tastingNotes: "Süß-cremig, Kokos", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Olivenlake", group: "Sonstiges", subGroup: "", category: "Würzflüssigkeit", abv: "", tastingNotes: "Salzig-herb", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Worcestersauce", group: "Sonstiges", subGroup: "", category: "Würzsauce", abv: "", tastingNotes: "Würzig-salzig, umami", story: "", service: "", alternatives: "", production: "", allergens: "Enthält Fisch (Sardellen)" },
  { name: "Tabasco", group: "Sonstiges", subGroup: "", category: "Würzsauce (Chili)", abv: "", tastingNotes: "Scharf-essigsauer", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Citrus-Säure", group: "Sonstiges", subGroup: "", category: "Säuerungsmittel · Eigenherstellung", abv: "", tastingNotes: "Rein sauer, geschmacksneutral", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Säure-Mischung", group: "Sonstiges", subGroup: "", category: "Säuerungsmittel · Eigenherstellung", abv: "", tastingNotes: "Sauer, rezepturabhängig", story: "", service: "", alternatives: "", production: "", allergens: "" },
  { name: "Brauner Zucker", group: "Sonstiges", subGroup: "", category: "Süßungsmittel", abv: "", tastingNotes: "Süß, leicht karamellig", story: "", service: "", alternatives: "Zuckersirup", production: "", allergens: "" },
  { name: "Beery Campari-Vermouth-Mix", group: "Sonstiges", subGroup: "", category: "Haus-Mix · Eigenherstellung", abv: "", tastingNotes: "Bitter-süß, Campari/Wermut-Basis", story: "", service: "", alternatives: "", production: "", allergens: "Enthält Sulfite (weinbasiert)" },
  { name: "Pre-Mix", group: "Sonstiges", subGroup: "", category: "Haus-Mix · Eigenherstellung, unspezifisch", abv: "", tastingNotes: "Rezepturabhängig", story: "", service: "", alternatives: "", production: "", allergens: "" },
];
